fix: fixed i-lock-page-scroll on ios
V4Fire/Client pull request #1059
Opened 2023-11-28 12:12 UTC by Gannicus91

2023-11-28 14:03 UTC, kobezzza commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +	protected static initIOSScrollableNodeListeners(component: iBlock, scrollableNode?: Element): void {
В характеристике не должно быть protected

2023-11-28 14:53 UTC, Gannicus91 commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +	protected static initIOSScrollableNodeListeners(component: iBlock, scrollableNode?: Element): void {
а почему? характеристика это же по сути абстрактный класс с дефолтными реализациями. Я понимаю почему это справедливо для нестатичных методов, но почему у него не может быть защищенных статичных методов, недоступных снаружи? 

кстати в `i-observe-dom` такое тоже есть

2023-11-29 05:54 UTC, gretzkiy commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +	protected static scrollableNodesList: Element[] = [];
Мне кажется, тут будет лучше использовать `WeakSet`, если все, что тебе нужно делать с этим контейнером, это поиск

2023-11-29 13:15 UTC, kobezzza commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +	protected static initIOSScrollableNodeListeners(component: iBlock, scrollableNode?: Element): void {
В i-observe-dom другая ситуация. Там статический метод, просто статический, а не является дефолтной реализацией, а тут ты предполагаешь, что этот метод будет доступен из компонента. И вот это не верно. Хар-ка наделяется компонент только публичным API. Если ты хочешь сделать protected в рамках хар-ки, то тогда тебе надо сделать через композицию внешний класс, как в i-history.

2023-11-29 13:35 UTC, Gannicus91 commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +	protected static initIOSScrollableNodeListeners(component: iBlock, scrollableNode?: Element): void {
напротив я хочу, чтобы метод был доступен только для хар-ки и не был дефолтной реализацией - я не думаю что это поведение стоит как-то переопределять или где-то еще использовать

я просто вынес кусок кода в метод, чтобы не загрязнять код метода lock()

еще думал вынести вообще из класса и в хелперах где-то хранить

2023-11-29 13:42 UTC, shining-mind requested changes

2023-11-29 13:42 UTC, shining-mind commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +				this.scrollableNodes = new WeakSet<Element>();
```suggestion
				iLockPageScroll.scrollableNodes = new WeakSet<Element>();
```

2023-11-29 13:42 UTC, shining-mind commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +		this.initIOSScrollableNodeListeners(component, scrollableNode);
```suggestion
		iLockPageScroll.initIOSScrollableNodeListeners(component, scrollableNode);
```

2023-11-29 13:42 UTC, shining-mind commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +		if (is.mobile !== false && is.iOS !== false && scrollableNode != null) {
в данном случае лучше сделать проверку предусловий и выйти из функции, чтобы всё тело функции не было в одном большом if

2023-11-29 13:42 UTC, shining-mind commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +		this.initIOSScrollableNodeListeners(component, scrollableNode);
И не проще ли этот блок перенести внутрь `if (is.mobile...) if (is.iOS...)`, тогда внутри метода не надо будет делать эту проверку

2023-11-29 13:42 UTC, shining-mind commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +					if (scrollTarget.scrollHeight > scrollTarget.clientHeight || !scrollTarget.parentElement) {
Может это условие добавить прямо в `while`?

2023-11-29 13:42 UTC, shining-mind commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> -			$a.clearAll({group});
Так, а теперь очистки вообще не будет?

2023-11-29 13:43 UTC, shining-mind commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +	protected static initIOSScrollableNodeListeners(component: iBlock, scrollableNode?: Element): void {
Хелперы - нормальное решение

2023-11-29 14:49 UTC, Gannicus91 commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> -			$a.clearAll({group});
она здесь не нужна

если r[$$.isLocked] === true значит все промисы общие уже отработали и остались крутиться только слушатели на ios, а их прибивать ненужно

2023-12-04 16:30 UTC, shining-mind approved these changes

2023-12-07 07:28 UTC, kobezzza commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +			is.mobile === false ||
Лучше условие что это иос вынести внаружу

2023-12-07 07:41 UTC, kobezzza commented on src/traits/i-lock-page-scroll/i-lock-page-scroll.ts
> +	 * Set of scrollable nodes for iOS platform
```suggestion
	 * A set of scrollable nodes for the iOS platform
```

2023-12-07 07:50 UTC, kobezzza approved these changes

2023-12-07 08:58 UTC, merged