feat: added useScrollSnap flag for slider component
V4Fire/Client pull request #1095
Opened 2024-01-25 12:06 UTC by DmitryYegorov

2024-01-25 12:29 UTC, shining-mind requested changes

2024-01-25 12:29 UTC, shining-mind commented on src/components/base/b-slider/b-slider.ts
> +	ModsDecl, prop
Обрати внимание, что при многострочном импорте мы группируем свойства, например декораторы связанные с DSL компонентов сгруппированы вместе. Потому prop стоит разместить выше.

Также обязательно, чтобы каждый элемент шел с новой строки

2024-01-25 12:29 UTC, shining-mind commented on src/components/base/b-slider/b-slider.ss
> +			< template v-if = useScrollSnap
Кажется тут условие перепутано, кажется должно быть наоборот.

2024-01-25 12:29 UTC, shining-mind commented on src/components/base/b-slider/b-slider.ts
> +	@field()
Это должен быть prop, а не field. Потому что field это стейт.

2024-01-25 12:29 UTC, shining-mind commented on src/components/base/b-slider/props.ts
> +	/**
Описание идет над декоратором

2024-01-25 12:29 UTC, shining-mind commented on src/components/base/b-slider/b-slider.ts
> +	@field()
UPD: заметил, что ниже есть проп. Пропы нормально отображаются в шаблоне их не надо переопределять как филды.

2024-01-25 12:29 UTC, shining-mind commented on src/components/global/g-slider/CHANGELOG.MD
Надо заполнить

2024-01-25 12:29 UTC, shining-mind commented on src/components/global/g-slider/README.MD
Надо дать описание модулю и привести примеры использования

2024-01-25 12:29 UTC, shining-mind commented on src/components/global/g-slider/g-slider.ss
> +- block index->scrollSnapSlider(items = [])
это должен быть template, посмотри ещё раз как сделан `b-skeleton.ss`

2024-01-25 12:29 UTC, shining-mind commented on src/components/global/g-slider/g-slider.ss
не указан namespace

2024-01-25 12:29 UTC, shining-mind commented on src/components/global/g-slider/g-slider.styl
> +	& > *
По моему тут не нужен амперсанд

2024-01-26 11:05 UTC, shining-mind reviewed
Надо всё-таки сделать истории для g-slider (storybook), а также написать юнит-тесты для режима useScrollSnap компонента b-slider.

Примеры историй есть у b-button, b-bottom-slide

2024-01-26 11:05 UTC, shining-mind commented on src/components/global/g-slider/README.MD
> +## Scroll Snap API
Описание дефолтного API наверное смысла делать нет, можно оставить ссылку на MDSN. А вот сделать примеры с каждый из свойств - имеет смысл. Что я имею в виду?

Например, можно сказать, если вы хотите задать произвольные точки "приклеивания" скролла, то добавить scroll-snap-align к нужному слайду (и привести пример разметки).

Примерно в таком стиле.

2024-01-26 11:05 UTC, shining-mind commented on src/components/global/g-slider/g-slider.ss
> +- include 'components/base/b-slider/modules/**/*.ss'|b
b-slider?

2024-01-26 11:05 UTC, shining-mind commented on src/components/global/g-slider/g-slider.ss
> +- include 'components/base/b-slider/modules/**/*.ss'|b
Думаю этот include можно вообще дропнуть, т.к. мы не предполагаем его расширение.
Если ты видишь много вариаций хелперов, тогда этот файл лучше делать как b-skeleton

2024-01-26 11:05 UTC, shining-mind commented on src/components/global/g-slider/g-slider.styl
> +  & > *
Без амперсанда точно не работает?

2024-01-26 11:05 UTC, shining-mind commented on src/components/pages/p-v4-components-demo/p-v4-components-demo.ss
> +- include 'components/global/g-slider/g-slider.ss'|b
Надо вернуть этот файл к исходному виду.

2024-01-29 13:11 UTC, shining-mind commented on src/components/global/g-slider/README.MD
> +   - `.glider__slide_snap_end`
тут опечатка кажись

2024-01-29 13:11 UTC, shining-mind commented on src/components/global/g-slider/g-slider.stories.ts
> +		'slot-default': 'Content or slides'
Здесь лучше сделать пример с реальными слайдами. И добавить все примеры из README.

Это можно сделать так:

```js

args: {
   children: [
     {type: 'img', attrs: {src: '...'}},
     {type: 'img', attrs: {src: '...'}},
     
   ]
}
```

2024-01-29 13:11 UTC, shining-mind commented on src/components/pages/p-v4-components-demo/p-v4-components-demo.ss
> +
Надо удалить отступы пустые

2024-01-30 13:10 UTC, shining-mind commented on src/components/base/b-slider/README.md
> +The flag that turning off / on using of Scroll Snap slider (component g-slider).
Надо поправить грамматические ошибки

2024-01-30 13:10 UTC, shining-mind commented on src/components/base/b-slider/CHANGELOG.md
> +* Added the option `useScrollSnap` for the b-slider component, which enables the mode of using `scroll snap` instead of handling touch events.
Формулировка плохо воспринимается, надо перефразировать

2024-01-30 13:10 UTC, shining-mind commented on src/components/base/b-slider/b-slider.ts
> +			throw new Error("You can't use `useScrollSnap` in `slide` mode");
```suggestion
			throw new Error("Can't enable scroll snap in `slide` mode");
```

2024-01-30 13:10 UTC, shining-mind commented on src/components/base/b-slider/b-slider.ts
> +	protected validateData(): void {
```suggestion
	protected validateProps(): void {
```

2024-01-30 13:10 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		await test.expect(page.locator('div:nth-child(2) > .b-slider__window > .g-slider')).toBeVisible();
Ну, наверное такой специфичный локатор не стоит делать - достаточно проверить, что внутри b-slider есть g-slider

2024-01-30 13:10 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	test('should throw error if slider in `slide` mode uses the CSS Scroll Snap (useScrollSnap = true)', async ({page}) => {
```suggestion
	test('should throw error `useScrollSnap = true` and `mode = slide`', async ({page}) => {
```

2024-01-30 13:10 UTC, shining-mind commented on src/components/global/g-slider/g-slider.stories.ts
> +	argTypes: {
```suggestion
	argTypes: {}
```

2024-01-31 07:58 UTC, bonkalol commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	});
поддерживаю Артема, нужны тесты на то, что это свайпается, для этого есть специальный модуль Gestures который так же используется и для тестов b-slider

2024-01-31 07:59 UTC, bonkalol commented on src/components/base/b-slider/b-slider.ts
> +	protected validateProps(): void {
jsdoc

2024-01-31 08:01 UTC, bonkalol commented on src/components/global/g-slider/README.md
> +  += self.getTpl('g-slider/')()
да походу смысла от шаблона нет, потому что куда проще просто написать .g-slider, а не импортить шаблон и писать длинную портяну

плюс если используешь просто < .g-slider - то куда проще добавлять классы и атрибуты, нежели прокидывать в блок

2024-01-31 08:02 UTC, bonkalol commented on src/components/global/g-slider/README.md
> +  += self.getTpl('g-slider/')()
или шаблон нужен для стори?

2024-01-31 11:14 UTC, DmitryYegorov commented on src/components/global/g-slider/README.md
> +  += self.getTpl('g-slider/')()
Да, ты прав

2024-01-31 13:37 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		swipeSlider = await renderSlider(page, {
нет смысл создавать все слайдеры для каждого теста, надо в каждом тест-кейсе создавать только один необходимый слайдер

2024-01-31 13:37 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		await test.expect
можно просто использовать [test.waitTimeout](https://playwright.dev/docs/api/class-page#page-wait-for-timeout)

2024-02-01 07:54 UTC, bonkalol commented on src/components/global/g-slider/g-slider.styl
> +		height 100vh
никаких 100vh, я захочу слайдер поменьше и как мне быть, пусть по контейнер подстраивается

2024-02-02 08:05 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		test.expect(await current(scrollSnapSlider)).toBe(0);
```suggestion
		await test.expect(current(scrollSnapSlider)).toBeResolvedTo(0);
```

2024-02-02 08:07 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +			const sliderContainer = document.getElementsByClassName('g-slider')[0];
А чем обычный `document.querySelector('.g-slider')` не подошел?

2024-02-02 08:20 UTC, bonkalol commented on src/components/base/b-slider/b-slider.ts
> +		console.log('onStart');
удали

2024-02-02 08:20 UTC, bonkalol commented on src/components/base/b-slider/b-slider.ts
> +		console.log('onMove');
удали

2024-02-02 08:20 UTC, bonkalol commented on src/components/base/b-slider/props.ts
> +	 * The flag that disables/enables the use of the Scroll Snap slider (g-slider component).
Прогони через gpt, есть грамматические ошибки

2024-02-02 08:21 UTC, bonkalol commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +			await test.expect(page.locator('#swipe_slider .g-slider')).not.toBeVisible();
toBeHidden же

2024-02-02 08:21 UTC, bonkalol commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +			await test.expect(page.locator('#swipe_slider .g-slider')).not.toBeVisible();
тут и ниже

2024-02-02 08:23 UTC, bonkalol commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		const scrollSnapSlider = await renderSlider(page, {
Думается надо хотя бы небольшое ожидание добавить (если проверяем что не крутится сам)

Но сейчас вообще не понятно почему он не должен скролиться, или должен сам

пропы никак не указывают на то что он должен/не должен автоматически прокручиваться

2024-02-02 08:25 UTC, bonkalol commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	test('swipe: should snap slides to the edge of the container', async ({page}) => {
в тесте написано свайп, а по факту ты сам двигаешь контейнер, используй специальный модуль Gestures чтобы реализовать проверку на реагирование на свайпы

представим ситуацию что ты неправильно биндишь обработчики и для g-slider у тебя биндятся touch события, которые не должны. Тестом с Gestures ты можешь это отловить, тестом где ты просто берешь и ставишь значение - нет. Да и вообще, тесты должны эмитировать поведение пользователя (по большой части), я думаю пользователи используют жесты, чтобы прокручивать, а не ставят scrollLeft )

2024-02-02 08:27 UTC, bonkalol commented on src/components/global/g-slider/README.md
> +```
укажи язык здесь и ниже

2024-02-02 08:27 UTC, bonkalol commented on src/components/global/g-slider/README.md
> +You can use this component using simple block with specials modifiers
прогоняй текст через gpt, чет нигде нет точек например

2024-02-02 08:31 UTC, bonkalol commented on src/components/global/g-slider/README.md
> +< .g-slider.&__horizontal_true
.g-slider.&__horizontal_true при использовании в шаблоне у тебя на самом деле скомпилируется в .g-slider.componentName__horizontal_true

тобишь здесь должно быть на самом деле `[.g-slider].&_horizontal_true`

Обрати внимание, перед horizontal всего один _, у нас конвенция такая: `имя-блока__имя-элемента_имя-модификатора_значение модификатора`

А вот касательно `__slide_snap_start `, тут все верно, получается должно быть финально так: `.g__slide_snap_start`, то есть элемент slide, snap мод и start значение мода

2024-02-02 08:32 UTC, bonkalol commented on src/components/base/b-slider/README.md
> +The flag that disables/enables the use of the Scroll Snap slider (g-slider component).
Весь текст через gpt прогоняй на грамматические ошибки

2024-02-02 08:33 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	test('swipe: should snap slides to the edge of the container', async ({page}) => {
Мы пробовали жесты, но они не работают, потому что класс Gestures эмитит события тач искуственно и скролл не происходит

2024-02-02 08:35 UTC, shining-mind commented on src/components/global/g-slider/README.md
> +< .g-slider.&__horizontal_true
Точно `.g__slide_snap_start`, а не `.g-slider__slide...`?

2024-02-02 09:02 UTC, bonkalol commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	test('swipe: should snap slides to the edge of the container', async ({page}) => {
Точняк, mouse.wheel не подойдет тогда? https://playwright.dev/docs/api/class-mouse#mouse-wheel

2024-02-02 09:02 UTC, bonkalol commented on src/components/global/g-slider/README.md
> +< .g-slider.&__horizontal_true
Поправил

2024-02-02 09:03 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	test('swipe: should snap slides to the edge of the container', async ({page}) => {
Подойдет, но на самом деле хотелось бы именно свайп протестировать

2024-02-02 10:02 UTC, bonkalol commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	test('swipe: should snap slides to the edge of the container', async ({page}) => {
маковсикие мышки генерят mousewheel в бок на таких слайдерах, так что все валидно

2024-02-05 12:38 UTC, shining-mind commented on src/components/base/b-slider/README.md
> +The flag that disables/enables the use of the scroll snap slider (g-slider component).
Думаю надо это описание сделать более лаконичным.

2024-02-05 12:39 UTC, shining-mind commented on src/components/base/b-slider/props.ts
> +	 * The flag that disables/enables the use of the scroll snap slider (g-slider component).
Описание сделать более лаконичным, как в README

2024-02-05 12:39 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +
```suggestion
```

2024-02-05 12:40 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +			await test.expect(page.locator('#scroll_slider .g-slider')).toBeHidden();
А откуда берется ID scroll_slider - ты же его не прокидываешь?

2024-02-05 12:40 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	test('should throw error `useScrollSnap = true` and `mode = slide`', async ({page}) => {
```suggestion
	test('should throw error with `useScrollSnap = true` and `mode = slide`', async ({page}) => {
```

2024-02-05 12:41 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +	test('shouldn\'t automatically scroll', async ({page}) => {
Богдан уже писал, что описание теста неудачное, надо добавить пояснение, например:

```
"should not automatically scroll when `autoSliderInterval` prop is set"
```

2024-02-05 12:43 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		await scrollSnapSlider.evaluate((ctx) => ctx.unsafe.async.sleep(200));
Странно, что мы задаем время переключения слайда равной 1 секунде, но при этом ждём всего 200ms

2024-02-05 12:44 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		const position = await page.evaluate(() => {
Можно в одну строчку:

```js
const position = await page.evaluate(() => Number(document.querySelector('.g-slider')?.scrollLeft));
```

2024-02-05 12:45 UTC, shining-mind commented on src/components/global/g-slider/README.md
> +You can use this component using a simple block with special modifiers.
Ну, g-slider это все-таки не компонент, а просто глобальный блок (в терминах БЭМ)

2024-02-05 12:47 UTC, shining-mind commented on src/components/global/g-slider/g-slider.styl
> +		height 300px
Эм, мы вроде договаривались, что тут должно быть 100%?

2024-02-05 13:52 UTC, DmitryYegorov commented on src/components/global/g-slider/g-slider.styl
> +		height 300px
точно, забыл убрать

2024-02-05 16:50 UTC, shining-mind commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		await scrollSnapSlider.evaluate((ctx) => ctx.unsafe.async.sleep(3000));
Лучше не ставить такой большой таймаут, так как это замедляет выполнение тестов в CI. Стоит сделать небольшой autoSlideInterval и чуть больше таймаут, но это должны быть десятки ms, в крайнем случае сотни ms.

2024-02-06 09:57 UTC, DmitryYegorov commented on src/components/base/b-slider/test/unit/scroll-snap.ts
> +		await scrollSnapSlider.evaluate((ctx) => ctx.unsafe.async.sleep(3000));
поправил

2024-03-07 14:41 UTC, kobezzza approved these changes

2024-03-07 15:19 UTC, merged