feat: added property 'layer' for ComponentMeta
V4Fire/Client pull request #1130
Opened 2024-02-12 12:40 UTC by DmitryYegorov

2024-02-12 12:47 UTC, shining-mind requested changes

2024-02-12 12:47 UTC, shining-mind commented on package.json
> +    "modify-source-webpack-plugin": "^4.1.0",
Нужно указать точную версию

2024-02-12 12:47 UTC, shining-mind commented on src/core/component/reflect/interface.ts
> +	layer?: string;
Нужно описание jsdoc

2024-02-12 12:47 UTC, shining-mind commented on webpack.config.js
> +const {ModifySourcePlugin, ReplaceOperation} = require('modify-source-webpack-plugin');
Надо внести эти изменения в соответствующий файл внутри директории `build/webpack`

2024-02-12 12:47 UTC, shining-mind commented on webpack.config.js
> +						operations: [new ReplaceOperation('once', '$PACKAGE_NAME', packageJson.name)]
Разве он не заменит во всех слоях на имя текущего слоя? С таким успехом можно было использовать тот же defines plugin (см. build/globals.webpack.js)

2024-02-19 11:50 UTC, shining-mind commented on build/webpack/loaders/components-loader.js
> +	const componentRegExp = new RegExp(`(${path.sep}|\\|)(${validators.blockTypeList.join('|')})-.+?(${path.sep}|\\|)?`);
Инициализацию регулярок надо вынести за пределы функции

2024-02-19 11:50 UTC, shining-mind commented on build/webpack/module/rules/ts.js
> +				loader: path.resolve('build/webpack/loaders/components-loader.js'),
тут можно просто имя лоадера указать, главное, чтобы он был в папке лоадеров, т.е.:

```js
{
  loader: 'components-loader'
}
```

2024-02-19 11:50 UTC, shining-mind commented on build/webpack/module/rules/ts.js
> +				loader: path.resolve('build/webpack/loaders/components-loader.js'),
Это работает благодаря настройкам в файле `build/webpack/resolve-loader.js`

2024-02-19 11:50 UTC, shining-mind commented on build/webpack/module/rules/ts.js
> +					...typescript.client
Не понятно, зачем этому лоадеру опции от TS

2024-02-19 11:50 UTC, shining-mind commented on src/components/super/i-block/i-block.ts
> +@component(
Потом не забудь откатить обратно эти правки

2024-02-19 11:50 UTC, shining-mind commented on src/core/component/reflect/constructor.ts
> +			const parentComponent = components.get(parent);
немного непонятно зачем эта правка

2024-02-20 10:39 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +const prefixPathRegExp = new RegExp(`.+(${path.sep}|\\|)src`);
```suggestion
const prefixPathRegExp = new RegExp('.+[\\/]src')
```

2024-02-20 10:39 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +const prefixPathRegExp = new RegExp(`.+(${path.sep}|\\|)src`);
если нужно проверить, что в позиции стоит один из символов, то лучше использовать  квадратные скобки (символьные классы).

2024-02-20 10:39 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +const prefixPathRegExp = new RegExp(`.+(${path.sep}|\\|)src`);
кстати немного непонятно зачем ты делаешь проверку на пустоту в конце перечисления `(${path.sep}|\\|)` ведь у тебя до этого стоит `.+`, где плюс обозначает 1 или больше.

То есть в случае с пустым разделителем сюда попадут строки вида:

`some/pathsrc`, `any/pathsrc` и т.д. 

Что точно не желаемый результат, проверить можешь тут https://regex101.com/

2024-02-20 10:39 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +	const prefixPath = filePath.match(prefixPathRegExp)[0];
Я бы добавил группу в регулярное выражение, что сразу извлечь путь до `src` и не использовать относительный require

2024-02-20 10:39 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +	const packageJson = require(`${prefixPath}/../package.json`);
Может так записать?
```suggestion
	return require(`${prefixPath}/../package.json`).name;
```

2024-02-20 10:39 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +
Отступ лишний

2024-02-20 10:39 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +const setComponentLayerTransformer = (context) => (sourceFile) => {
Надо описать `@returns`

2024-02-20 10:39 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +		if (node.kind === ts.SyntaxKind.CallExpression &&
Линтер не ругается на то, что перенос вровень с if?

2024-02-20 10:39 UTC, shining-mind commented on src/core/component/meta/interface/index.ts
> +	 * The package name where component is defined or override
```suggestion
	 * The name of the package in which component is defined or overridden
```

2024-02-20 10:39 UTC, shining-mind commented on src/core/component/reflect/constructor.ts
> +	const layer = declParams?.layer ?? undefined;
Мне кажется, что здесь лишний оператор `??`. `layer` ведь и так будет undefined, потому:

```suggestion
	const layer = declParams?.layer;
```

2024-02-21 14:45 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +function isComponent(path) {
`isInsideComponent` - всё таки функция проверяет, что путь содержит компонент

2024-02-22 09:16 UTC, shining-mind commented on build/ts-transformers/set-component-layer.js
> +
!

2024-02-22 09:21 UTC, shining-mind approved these changes

2024-02-26 10:24 UTC, kholstinin commented on build/ts-transformers/set-component-layer.js
> +function getLayerName(filePath) {
jsdoc

2024-02-26 10:24 UTC, kholstinin commented on build/ts-transformers/set-component-layer.js
> +const setComponentLayerTransformer = (context) => (sourceFile) => {
Тут нужен большой jsdoc с описание что делать трансформер и обязательно добавить `@example` что на входе трансформера и что на выходе

2024-03-07 13:20 UTC, kobezzza approved these changes

2024-03-07 13:21 UTC, merged