feat(b-dynamic-page): add API to save scroll with keepAlive
V4Fire/Client pull request #1229
Opened 2024-04-16 11:00 UTC by ItMaga

2024-04-17 12:24 UTC, kobezzza commented on src/components/base/b-dynamic-page/modules/scroll-manager.ts
> +export default class ScrollManager {
А если у нас класс только со статическими методами, не лучше ли сделать обычные экспортируемые функции

2024-04-17 12:25 UTC, kobezzza commented on src/components/base/b-dynamic-page/modules/scroll-manager.ts
> +		el.setAttribute(horizontalScrollAttribute, String(el.scrollLeft));
А почему только scrolLeft? Ведь у элемента может быть и overlflow-y

2024-04-17 12:30 UTC, kobezzza commented on src/components/base/b-dynamic-page/b-dynamic-page.ts
> +					r.emit('beforeRemovePage', <OnBeforeRemovePage>{saveScroll: ScrollManager.saveScrollIntoAttribute});
И еще, мб тогда как раз сделать 2 класса (раз ты используешь классы: один для паблик АПИ, другой для внутреннего. И тогда не придется явно типы кастить.

2024-04-17 12:32 UTC, kobezzza commented on src/components/pages/p-v4-dynamic-page1/p-v4-dynamic-page1.ts
> +		this.console.log(this.$refs.horizontalScroll);
Это не забыл удалить?

2024-04-17 12:33 UTC, kobezzza commented on src/components/pages/p-v4-dynamic-page1/p-v4-dynamic-page1.ts
> +	protected saveSliderScroll({saveScroll}: OnBeforeRemovePage): void {
Может лучше завести отдельный dummy компонент, а то тест выходит размазанным.

Например, https://github.com/V4Fire/Client/blob/v4/src/components/friends/block/index.ts#L20

2024-04-17 12:52 UTC, shining-mind commented on src/components/base/b-dynamic-page/modules/scroll-manager.ts
> +export default class ScrollManager {
Я тоже поддерживаю, что надо экспортировать функции

2024-04-17 13:05 UTC, shining-mind requested changes

2024-04-17 13:05 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/events.ts
> +			globalThis.onBeforeRemovePageCalls = 0;
Можно создать JSHandle:

```js
    const count = await page.evaluateHandle(() => ({value: 0}));

		await target.evaluate((ctx, count) => {
			ctx.watch('rootEmitter:onBeforeRemovePage', () => {
				count.value++;
			});
		}, count);

    const calls = await count.evaluate(({value}) => value);
```

2024-04-17 13:05 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/scroll.ts
> +		await test.expect(scroll.isHidden()).resolves.toBe(true);
```suggestion
		await test.expect(scroll).toBeHidden();
```

2024-04-17 13:32 UTC, ItMaga commented on src/components/base/b-dynamic-page/modules/scroll-manager.ts
> +export default class ScrollManager {
@shining-mind Что думаешь, если использовать публичный и приватный класс? Как Андрей тут написал https://github.com/V4Fire/Client/pull/1229#discussion_r1568765331

2024-04-17 13:33 UTC, shining-mind commented on src/components/base/b-dynamic-page/modules/scroll-manager.ts
> +export default class ScrollManager {
А в чём профит использовать utility классы? Их изначально придумали в Java, так как там нельзя создавать функции.

2024-04-18 06:27 UTC, ItMaga commented on src/components/base/b-dynamic-page/modules/scroll-manager.ts
> +export default class ScrollManager {
Убрал класс, сделал через функции

2024-04-18 08:29 UTC, bonkalol commented on src/components/base/b-dynamic-page/helpers/scroll.ts
> +	const elementsWithHorizontalScroll = page.querySelectorAll(`[${scrollAttribute}]`);
А зачем выбирать на странице узлы? Почему бы не заиспользовать WeakSet? querySelector по всей странице на огромных страницах - не самая быстрая операция

2024-04-18 08:31 UTC, bonkalol commented on src/components/base/b-dynamic-page/helpers/scroll.ts
> +	const elementsWithHorizontalScroll = page.querySelectorAll(`[${scrollAttribute}]`);
Или задумка в том, что я рукам могу поставить этот атрибут в шаблоне?

2024-04-19 13:04 UTC, kobezzza approved these changes

2024-04-19 13:22 UTC, kobezzza approved these changes

2024-04-19 13:23 UTC, merged