fix #1275
V4Fire/Client pull request #1308
Opened 2024-06-14 11:13 UTC by boikovdv

2024-06-14 13:36 UTC, shining-mind commented on src/components/base/b-dynamic-page/b-dynamic-page.ts
> +		return !/^(?:hook)(?::\w+(-\w+)*|-change)$/.test(event.dasherize());
```suggestion
		return !/^hook(?::\w+(-\w+)*|-change)$/.test(event.dasherize());
```

2024-06-17 10:22 UTC, kobezzza commented on CHANGELOG.md
> +* Fix hookChange event processing for activate/deactivate component `core/component/init`
Надо сделать более понятное описание

2024-06-17 10:23 UTC, kobezzza commented on src/components/base/b-dynamic-page/b-dynamic-page.ts
> +		return !/^hook(?::\w+(-\w+)*|-change)$/.test(event.dasherize());
Это надо отразить в доке. сейчас там написано другое

2024-06-17 10:29 UTC, kobezzza commented on src/core/component/init/states/created.ts
> +			p.$on('onHookChange', onActivation);
Надо написать тест на этот кейс

2024-06-25 10:46 UTC, shining-mind commented on CHANGELOG.md
> +* Fixed a typo in the hookChange event name for processing activate/deactivate component `core/component/init`
```suggestion
* Fixed a typo in the hookChange event name for processing activate/deactivate in component `core/component/init`
```

2024-06-25 10:46 UTC, shining-mind commented on CHANGELOG.md
> +* Fix component deactivation order, children must be deactivated first `core/component/init`
```suggestion
* Fixed the component deactivation order: children must be deactivated first `core/component/init`
```

2024-06-25 10:46 UTC, shining-mind commented on CHANGELOG.md
> +* Fix hookChange event should not bubble `bDynamicPage`
```suggestion
* Fixed an issue where the hookChange event should not bubble in `bDynamicPage`
```

2024-06-25 10:46 UTC, shining-mind commented on src/components/base/b-dynamic-page/CHANGELOG.md
> +* Fix hookChange event should not bubble
Поправить текст во всех CHANGELOG согласно основному

2024-06-25 10:46 UTC, shining-mind commented on src/components/super/i-block/i-block.ts
> +			this.$el.component = this;
Кажется это лишняя строка

2024-06-25 10:46 UTC, shining-mind commented on src/components/super/i-block/modules/activation/index.ts
> +		onDeactivated(component);
Коммент про деактивацию надо перенести вместе со строчкой. Также стоит пояснить, почему деактивация перенесана после вызова runHook

2024-06-25 10:46 UTC, shining-mind commented on src/core/component/init/test/unit/main.ts
> +test.describe('core init component deactivation', () => {
наверное имеет смысл выделить отдельный файл под тесты активации/деактивации, например, activation.ts

2024-06-25 10:46 UTC, shining-mind commented on src/core/component/init/test/unit/main.ts
> +		test.expect(await page.locator('#button1').evaluate((el: ComponentElement) => el.component?.hook)).toBe('deactivated');
ИМХО, лучше создать JSHandle на контекст компонент сразу. Вместо ID можно использовать ref:

```ts
const button1: JSHandle<bButton> = await target.evaluateHandle((ctx) => ctx.unsafe.$refs.button1);
```

Тогда assert будет выглядеть так:

```js
await test.expect(button1.evaluate((ctx) => ctx.hook)).toBeResolvedTo('deactivated');
```

2024-06-26 08:21 UTC, boikovdv commented on src/components/super/i-block/i-block.ts
> +			this.$el.component = this;
Если имеется ввиду nextTick, то он здесь необходим, поскольку вотчер срабатывает еще до того как vue заменит комент-ноду v-if на реальный компонент.

2024-06-26 11:36 UTC, shining-mind commented on src/components/super/i-block/i-block.ts
> +			this.$el.component = this;
Комментарий стоит на строке 94:

```js
this.$el.component = this;
```

Этот код дублируется на строке 101

2024-06-26 17:30 UTC, boikovdv commented on src/components/super/i-block/i-block.ts
> +			this.$el.component = this;
Это тоже умышленно, у телепорта 2 дом узла, сначала фиксится ссылка на компонент у одного, потом фиксится ссылка на правильный дом элемент у самого компонента и после чего фиксится уже ссылка на компонент у второго дом узла который переносится в телепорт-контейнер

2024-06-27 12:39 UTC, shining-mind commented on src/components/super/i-block/i-block.ts
> +			this.$el.component = this;
Надо оставить комментарий, иначе не понятно зачем оно так сделано

2024-06-27 13:16 UTC, shining-mind requested changes

2024-06-27 13:16 UTC, shining-mind commented on src/core/component/init/test/b-deactivation-component/index.js
> +	.dependencies('b-button');
b-bottom-slide надо добавить в зависимости

2024-06-27 13:16 UTC, shining-mind commented on src/core/component/init/index.ts
> +import('core/component/init/test/b-deactivation-component');
У нас принято, что тестовые компоненты имеют постфикс dummy, а ещё желательно, чтобы в префиксе было название модуля.

2024-06-27 13:16 UTC, shining-mind commented on src/core/component/init/test/unit/activation.ts
> +/*!
Я вспомнил, что у нас есть src/components/super/i-block/modules/activation/test/unit

Там как раз тестируется активация и деактивация. Предлагаю эти тесты перенести туда.

2024-06-27 13:16 UTC, shining-mind commented on src/core/component/init/test/unit/activation.ts
> +import type BDeactivationComponent from 'core/component/init/test/b-deactivation-component/b-deactivation-component';
```suggestion
import type bDeactivationComponent from 'core/component/init/test/b-deactivation-component/b-deactivation-component';
```

2024-06-27 13:16 UTC, shining-mind commented on src/core/component/init/test/unit/activation.ts
> +			return ctx.unsafe.$refs['button1'].hook;
```suggestion
			return ctx.unsafe.$refs.button1.hook;
```

2024-06-27 13:16 UTC, shining-mind commented on src/core/component/init/test/unit/activation.ts
> +		test.expect(await state).toBe('deactivated');
```suggestion
		await test.expect(state).toBeResolvedTo('deactivated');
```

2024-06-27 13:16 UTC, shining-mind commented on src/core/component/init/test/unit/activation.ts
> +	test('children button should be deactivated', async () => {
В описании не хватает условия when, например можно перефразировать так:
```js
test.describe('when parent component is deactivated', () => {
  test('child component should be deactivated', async () => {
    // ...
  });

  test('...', () => {});
})
```

или добавить в описание каждого теста условие, если нельзя все тесты объединить под общим describe

2024-07-19 13:06 UTC, kobezzza approved these changes

2024-07-25 09:12 UTC, shining-mind approved these changes

2024-07-26 11:00 UTC, merged