fix(b-virtual-scroll): `initLoadNext` canceling
V4Fire/Client pull request #1348
Opened 2024-07-19 14:37 UTC by ItMaga

2024-07-19 15:29 UTC, ItMaga commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			itemsForMount = this.componentFactory.produceMounted(componentItems, nodes);
@bonkalol Когда смотрели с Артемом это место, показалось, что mounted не совсем отражает суть и кажется что элементы уже смонтированы, а по факту они монтируются позже. Может будет идея как лучше назвать или мы не совсем поняли суть?

@shining-mind FYI

2024-07-19 16:03 UTC, bonkalol approved these changes

2024-07-19 16:04 UTC, bonkalol commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			itemsForMount = this.componentFactory.produceMounted(componentItems, nodes);
вообще, мне кажется что это должно быть учтено в dataProvider.get и врапинг в асинк должен быть там, иначе зачем я передаю async options, кажется это упущение что там не все завраплено просто

2024-07-19 16:06 UTC, bonkalol requested changes

2024-07-19 16:06 UTC, bonkalol commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			get = this.async.request(this.dataProvider.get(params[0], {showProgress: false}), params[1]);
вообще, мне кажется что это должно быть учтено в dataProvider.get и врапинг в асинк должен быть там, иначе зачем я передаю async options, кажется это упущение что там не все завраплено просто

2024-07-19 16:09 UTC, shining-mind commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			itemsForMount = this.componentFactory.produceMounted(componentItems, nodes);
Вообще, я сейчас смотрю в реализацию метода get, и по идее "сырой" запрос не должен начинаться до того как это станет возможно. https://github.com/V4Fire/Client/blob/91565b0b03b9dcf8ed31cc7984cba4bfb5c9a4d3/src/components/friends/data-provider/request.ts#L222-L229

Но такое ощущение, что async опции просто не применились изначально.

2024-07-19 16:12 UTC, kobezzza commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			get = this.async.request(this.dataProvider.get(params[0], {showProgress: false}), params[1]);
Да, dataProvider уже завернут в асинк

2024-07-19 16:12 UTC, shining-mind commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			itemsForMount = this.componentFactory.produceMounted(componentItems, nodes);
@ItMaga надо проверить ещё раз

2024-07-19 16:12 UTC, shining-mind commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			get = this.async.request(this.dataProvider.get(params[0], {showProgress: false}), params[1]);
https://github.com/V4Fire/Client/pull/1348#discussion_r1684593269

2024-07-19 16:16 UTC, shining-mind commented on src/components/friends/data-provider/request.ts
> +	const req = this.async.promise(ctx.waitPermissionToRequest().then(() => {
waitPermissionToRequest - и так уже завернут в async внутри, я предлагаю добавить возможносить прокидывать аргументы в этот метод

@kobezzza что думаешь?

2024-07-19 16:16 UTC, ItMaga commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			itemsForMount = this.componentFactory.produceMounted(componentItems, nodes);
Запрос и не начинается, но промис создается или ты не про это?

2024-07-19 16:17 UTC, shining-mind commented on src/components/base/b-virtual-scroll-new/b-virtual-scroll-new.ts
> +			itemsForMount = this.componentFactory.produceMounted(componentItems, nodes);
Да, верно.

2024-07-20 08:33 UTC, kobezzza commented on src/components/friends/data-provider/request.ts
> +	const req = this.async.promise(ctx.waitPermissionToRequest().then(() => {
Да, асинк опции должны прокидываться и в waitPermissionToRequest

2024-07-22 07:20 UTC, ItMaga commented on src/components/friends/data-provider/request.ts
> +	const req = this.async.promise(ctx.waitPermissionToRequest().then(() => {
А в данном случае не лучше обернуть и `waitPermissionToRequest` и запрос уже внутри? Чтобы не ставить в двух местах одинаковые асинк опции

Если я правильно понял, то если мы прокинем только в `waitPermissionToRequest`, после его резолва нам нужно ещё на сам запрос поставить асинк опции.

2024-07-22 08:20 UTC, shining-mind commented on src/components/friends/data-provider/request.ts
> +	const req = this.async.promise(ctx.waitPermissionToRequest().then(() => {
У нас два разных потока, если промис waitPermissionToRequest успеет зарезолвится, это не значит что запрос успеет завершится до момент как умрёт компонент.

Потому надо опции прокидывать и туда, и туда. Сейчас как раз упущение в том, что забыли их в промис прокинуть.

2024-07-22 08:43 UTC, shining-mind commented on src/components/traits/i-data-provider/i-data-provider.ts
> +		const opts = asyncOpts ?? {label: $$.waitPermissionToRequest, join: true};
мне кажется тут надо объединить опции с дефолтными

2024-07-22 08:50 UTC, ItMaga commented on src/components/traits/i-data-provider/i-data-provider.ts
> +		const opts = asyncOpts ?? {label: $$.waitPermissionToRequest, join: true};
А подскажи плз, почему так будет лучше? Я почему-то подумал это будет немного неявно, если мы передадим только group, а там добавится join

2024-07-22 08:52 UTC, shining-mind commented on src/components/traits/i-data-provider/i-data-provider.ts
> +		const opts = asyncOpts ?? {label: $$.waitPermissionToRequest, join: true};
Потому что у этого потока есть некоторое дефолтное поведение, которое должно сохраниться, как правило мы можем захотеть переопределить группу или label, чтобы иметь возможность очистить его.

2024-07-22 08:55 UTC, ItMaga commented on src/components/traits/i-data-provider/i-data-provider.ts
> +		const opts = asyncOpts ?? {label: $$.waitPermissionToRequest, join: true};
Понял, спасибо, поправил)

2024-07-22 14:35 UTC, shining-mind commented on src/components/friends/data-provider/request.ts
> +		.then((res) => this.async.request(res.data, asyncParams))
А почему в async.request завернул, а не this.async.promise?

2024-07-22 14:37 UTC, ItMaga commented on src/components/friends/data-provider/request.ts
> +		.then((res) => this.async.request(res.data, asyncParams))
Чтобы при очистке через cancelRequest уже после того, как async.request зарезолвился, мы могли очистить на этом моменте

2024-07-22 14:39 UTC, shining-mind commented on src/components/friends/data-provider/request.ts
> +		.then((res) => this.async.request(res.data, asyncParams))
Оставь комментарий почему здесь это необходимо

2024-07-22 14:47 UTC, shining-mind commented on src/components/friends/data-provider/request.ts
> +		.then((res) => this.async.request(res.data, asyncParams))
Тут не описано ключевое, зачем нужно два res.data отдельно заворачивать

2024-07-22 14:55 UTC, shining-mind approved these changes

2024-07-22 15:43 UTC, ItMaga commented on src/components/friends/data-provider/test/provider/index.ts
> +export default class FriendsDataProvider extends Provider {
А там же вырезается моником через `//#if runtime has dummyComponents`

2024-07-22 15:44 UTC, bonkalol commented on src/components/friends/data-provider/test/provider/index.ts
> +export default class FriendsDataProvider extends Provider {
src/components/friends/data-provider/test/provider/index.ts я тут просто dummy не вижу, точно оно там вырезается? если да - то закрывай

2024-07-22 15:56 UTC, ItMaga commented on src/components/friends/data-provider/test/provider/index.ts
> +export default class FriendsDataProvider extends Provider {
Точно вырезается

2024-07-22 15:57 UTC, bonkalol approved these changes

2024-07-24 11:33 UTC, kobezzza approved these changes

2024-07-24 12:33 UTC, merged