Added controls to the slider
V4Fire/Client pull request #645
Opened 2021-11-01 09:50 UTC by kholstinin

2021-11-01 09:51 UTC, kholstinin commented on src/base/b-slider/b-slider.ss
> +			< .&__control &
Хочу сделать рендер либо слота control, либо дефолтного контрола, пока не понимаю как.
Нужно ли в слоты контрола прокидывать что-то (например, обработчик клика) или это должен делать пользователь?

2021-11-01 09:51 UTC, kholstinin commented on src/base/b-slider/b-slider.ts
> +	@field()
Сделал филдами длину контента и текущий индекс

2021-11-01 09:54 UTC, kholstinin commented on src/base/b-slider/b-slider.ss
> +				:class = provide.elClasses(${(self.name() + '__control')|json}, {current: {active: i - 1 === current}}) |
Не очень нравится портянка из стилей b-slider__control__current вместе с b-slider__control__current__active_true
Можно ли оставить лишь b-slider__control__active_true/false?

2021-11-02 10:31 UTC, kobezzza commented on src/base/b-slider/b-slider.ss
> +			< .&__control &
Если хочется сделать поведение "или слот или дефолтнное содержимое", то это делается изи-пизи.

```
+= self.slot('control')
  < .&__control
    Bla bla
```

2021-11-02 10:34 UTC, kobezzza commented on src/base/b-slider/b-slider.ss
> +		< .&__controls
При написании кода в Snakeskin очень важно соблюдать правило, что, когда ситуация вложенная директива-внешняя директива, например,

```
< .foo
  < .bar
<.bla     
```

То между ними обязательно должен быть дополнительный перевод строки, что код визуально не "слипался". Это упрощает чтение и понимаение кода. Вот так, например.

```
< .foo
  < .bar

<.bla     
```

2021-11-02 10:37 UTC, kobezzza commented on src/base/b-slider/b-slider.ss
> +			< template &
А вот тут нет смысла разбить на несколько строчек, т.к. всего 2 аттрибута и они нормально читаются на одной строке.

```
< template i in getContentLength() | :key = i
```

2021-11-02 10:43 UTC, kobezzza commented on src/base/b-slider/b-slider.ss
> +				:class = provide.elClasses(${(self.name() + '__control')|json}, {current: {active: i - 1 === current}}) |
Тут что-то странно.

Элемент не может быть от элемента.

`b-slider__control__current`

Это не правильно.

Т.е. тут должно быть либо `&__control`, либо `&__current`. А еще можно использовать комбинацию классов. `.&__control.&__current` - т. е. несколько имен у элемента и можно удобно развозить стили в CSS.

+ Не понятно зачем ты заюзал такой страшный костыль с (${(self.name() + '__control')|json}. Но видимо, для того, чтобы сделать элемент от элемента)

> Можно ли оставить лишь b-slider__control__active_true/false?

Нужно.

2021-11-02 10:46 UTC, kobezzza commented on src/base/b-slider/b-slider.ss
> +				:class = provide.elClasses(${(self.name() + '__control')|json}, {current: {active: i - 1 === current}}) |
> Не очень нравится портянка из стилей b-slider__control__current

Потому что - это не правильно) Элемента от элемента не бывает, бывает только элемент блока. Т.е. `b-slider__control` или `b-slider__current`. А еще можно комбинировать и на один тег сделать несколько элементов через комбинацию классов. `.&__control.&__current`

> Можно ли оставить лишь b-slider__control__active_true/false?

Нужно)

> :class = provide.elClasses(${(self.name() + '__control')|json}

Никогда такое не делай)

2021-11-02 10:50 UTC, bonkalol requested changes

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				v-for = (i) in getContentLength() |
Вот тут странно, у нас есть геттер contentLegth и теперь появляется метод getContentLegth

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	protected getContentLength(): number {
У каждого метода обязательно должен быть JSDOC

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	protected onControlClick(index: number, animate: boolean = true): Promise<boolean> {
Обработчики обычно в самом низу

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				v-for = (i) in getContentLength() |
v-for = i in something, то есть без ()

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				:class = provide.elClasses(${(self.name() + '__control')|json}, {current: {active: i - 1 === current}}) |
`provide.elClasses({control: {active: i - 1 === current}})` вот так не сделает трюк?

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +		< .&__controls
Отступами отбей блоки

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				ref = control |
Ты здесь добавил ref но нигде не используешь рефу

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +			< template &
Мне кажется проще тут разбить таки на 2 и придерживаться правила 2 директива - разбиваем, 1 - нет (по крайней мере я так делают), хотя бывает даже 1 строку переношу если длинное имя элемента или директива длинной получилась

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				v-for = i in getContentLength() |
тут кажется можно же просто v-for = i in length и делать этот доп метод

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				+= self.slot('control')
Надо бы еще придумать как ставить активный класс если нам передали слот, не нарушая инкапсуляции стилей при это, чтобы не писать такое:

```
p-cps-index
  .b-slider__control_active_true &__el
    background-color red
```

Может тут на $parent смотреть и брать его component name и на его основе делать `b-${componentName}_slider-control_active_true`?

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.styl
> +		position absolute
У нас есть классный хелпер

```
absolute left 0 bottom -15px
```

2021-11-02 10:50 UTC, bonkalol commented on src/base/b-slider/b-slider.styl
> +		width 10px
Есть хелпер size 10px

2021-11-02 10:51 UTC, kobezzza commented on src/base/b-slider/b-slider.styl
> +		width 10px
Тут можно использовать функцию size, чтобы сразу задать высоту и ширину. + В стилях V4 нельзя писать любые стилистически элементы: цвет, размер, шрифт. Т. к. мы не знаем какие стили будут в проекте, который подключает V4. Но если по каким то причинам, такие стили все таки нужно заюзать (например, у нас там зависимость от размера), то такие стили должны быть параметрами класса стилей. Например,

```
$p = {
  size: 10px
}

my-block extends i-block
  size $p.size
```

Такой стиль тривиально переопределяется в дочернем проекте или при наследовании одного компонента от другого.

+ Проверь, что у тебя включен Styllint

2021-11-02 10:51 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	protected getContentLength(): number {
Нет описаний

2021-11-02 10:52 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	@field()
Неужели без этого никак? Изменение этих полей всегда будет приводить к перерисовкам шаблона компонента.

2021-11-02 11:59 UTC, kholstinin commented on src/base/b-slider/b-slider.ts
> +	@field()
Да, мне же нужно перерисовывать компонент при изменении количества слайдов. Я понимаю, что это не очень оптимально, но как это сделать иначе я пока не представляю

2021-11-02 13:26 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +		this.console.log('click', index);
Зачем это?

2021-11-02 13:29 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	@field()
У тебя есть куча способов сделать это:

1. Использовать API AsyncRender https://github.com/V4Fire/Client/blob/master/src/super/i-block/modules/async-render/index.ts#L73
2. Использовать директиву https://github.com/V4Fire/Client/tree/master/src/core/component/directives/update-on
3. Просто вызывать forceUpdate при изменении этих полей из кода, но только в том случае, если компонент юзает эти контроллы и ему действительно нужно перерисоваться

2021-11-02 13:31 UTC, kobezzza commented on src/base/b-slider/b-slider.ss
> +				+= self.slot('control')
У компонентов есть стандартный prop - classes

https://github.com/V4Fire/Client/blob/master/src/super/i-block/i-block.ts#L517

Единственно что, возможно сейчас оно не будет работать при установке модифкатора, но в таком случае просто нужно допилить Block.setElMod чтобы оно тоже это учитывало.

2021-11-02 13:31 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	 * Handler: switches to the specified slide by an index
```suggestion
	 * Handler: switches to a slide by the specified index
```

2021-11-02 13:32 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	 * @param index - slide index
```suggestion
   *
	 * @param index - slide index
```

2021-11-02 13:33 UTC, kobezzza commented on src/base/b-slider/b-slider.styl
> +		background-color #000
Я уже писал про то, что компонент не должен такое хардкодить.

2021-11-02 13:34 UTC, kobezzza commented on src/base/b-slider/b-slider.styl
> +		size $p.size
Параметр назван по дурацки. Совершенно не понятно из контекста size чего тут. Уж тогда бы сделал $p.controlSize или $p.control.size (такой вариант подойдет если нужно много опций)

2021-11-02 13:34 UTC, kobezzza commented on src/base/b-slider/b-slider.styl
> +		width: 100%
```suggestion
		width 100%
```

2021-11-02 13:34 UTC, kobezzza commented on src/base/b-slider/b-slider.styl
> +		absolute left 0 bottom -15px
Почему именно 15?

2021-11-02 13:34 UTC, kobezzza commented on src/base/b-slider/b-slider.styl
> +		border-radius 50%
Почему именно 50?

2021-11-02 13:35 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	protected getControlAmount(): number {
Гм, а почему нельзя просто трекать this.length?

2021-11-15 06:58 UTC, kholstinin commented on src/base/b-slider/b-slider.styl
> +		border-radius 50%
Чтобы контрол был круглым

2021-11-15 10:17 UTC, kholstinin commented on src/base/b-slider/b-slider.styl
> +		absolute left 0 bottom -15px
Это для дефолтного рендера контролов

2021-11-22 08:39 UTC, bonkalol commented on src/base/b-slider/b-slider.styl
> +		absolute left 0 bottom -15px
Кажется здесь это надо занести под theme_demo

2021-11-22 08:52 UTC, bonkalol requested changes

2021-11-22 08:52 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				v-for = index in getControlAmount() |
Почему просто `length` не подходит?

2021-11-22 08:52 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	protected getControlAmount(): number {
Зачем этот метод? `length` же есть? Ну и название этого метода намекает что это должен быть геттер

2021-11-22 08:52 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +		this.console.log('click', index);
Забыл удалить дебаг

2021-11-22 08:52 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				+= self.slot('control')
Я выше писал, что стоит предусмотреть установку активного класса на контрол в случае если контрол передали из вне

2021-11-22 08:52 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +					< .&__control &
Кстати что таки насчет asyncRender? Будем пробовать?

2021-11-22 08:52 UTC, bonkalol commented on src/base/b-slider/b-slider.ss
> +				+= self.slot('control')
Нужно написать тесты на контролы

2021-11-22 08:53 UTC, bonkalol commented
Тесты упали 👀

2023-05-02 09:42 UTC, closed without merging