Added requestAnimationFrame for b-slider
V4Fire/Client pull request #656
Opened 2021-11-15 14:57 UTC by ann-arzamm

resolves #170

2021-11-16 08:00 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +		return globalThis.matchMedia("(prefers-reduced-motion: reduce)").matches;
"" -> ''

2021-11-16 08:22 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +			{ content } = this;
Здесь ругается линтер, проверь что он у тебя установлен в редакторе кода (eslint)

2021-11-16 08:24 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	protected get doReducedMotion(): boolean {
Мне кажется это лучше вычислить один раз и закэшировать результат, я не знаю насколько эта штука производительная, но на всякий случай - давай кэшировать и не пытаться проверять на каждый фрейм

2021-11-16 08:25 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +			this.performSliderAnimation();
На самом деле не уверен что название метода подходит, мб performSliderMove?

2021-11-16 08:26 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +			this.performSliderAnimation();
А здесь учитывается `animate` параметр? В случае если я его в false передам - просто сразу прокрутит куда надо? Без анимации?

2021-11-16 08:27 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	 * Updates slide position
Тут наверное slider position?

2021-11-16 08:27 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	 * Updates slide position
Updates the slider position

2021-11-16 08:28 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +		this.performSliderAnimation();
отбей тут отступом от установки значений, как было раньше

2021-11-16 08:35 UTC, bonkalol requested changes

2021-11-16 08:35 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
>  			this.current = current;
Так же добавь в changelog изменения сделанный (./src/base/b-slider/changelog.md и ./changelog.md)

2021-11-16 08:35 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	protected performSliderAnimation(): void {
Нужно написать тесты на gestures для slider режима, https://github.com/V4Fire/Client/blob/master/src/base/b-bottom-slide/test/runners/gestures.js вот это можно использовать как пример

2021-11-16 08:36 UTC, bonkalol commented
@ann-arzamm замержи в эту ветку `master`, у нас была ошибка из-за которой пайпы с ошибками eslint завершались успехом

2021-11-17 07:59 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	protected performSliderAnimation(): void {
https://github.com/V4Fire/Client/tree/master/docs/tests дока по тестам

2021-11-18 12:40 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +		if (!content) {
```suggestion

		if (content == null) {
```

2021-11-18 12:42 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	 * True if all animations need to use requestAnimationFrame
```suggestion
	 * True if all animations need to use `requestAnimationFrame`
```

2021-11-18 12:45 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	get doReducedMotion(): boolean {
do не очень подходит для геттера, мб лучше needReduceMotion

+ Этот геттер точно не должен быть protected?

2021-11-18 12:45 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +	get shouldUseRAF(): boolean {
Имхо, это должен быть protected геттер

2021-11-18 12:45 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +		return this.browser.is.iOS === false;
А есть инфа почему такое?

2021-11-18 12:46 UTC, kobezzza commented on src/base/b-slider/b-slider.ts
> +			this.async.requestAnimationFrame(() => {
Вместо 3-х строчек можно

```js
this.async.requestAnimationFrame(this.updateSlidePosition, {label: $$.performSliderMove});
```

2021-11-29 13:17 UTC, ann-arzamm commented on src/base/b-slider/b-slider.ts
> +		return this.browser.is.iOS === false;
Почему используется проверка на iOS? @bonkalol: "для ios мы вырубали raf так как safari умеет тротлить и анимация начинает лагать, да и если не тротлит то все равно без raf лучше работает"

2021-11-29 17:52 UTC, ann-arzamm commented on src/base/b-slider/b-slider.ts
> +			this.performSliderAnimation();
Да, я не трогала накладываемый им через модификатор стиль, `swipe` отключает transition, убирая анимацию прокрутки. Проверяла, меняя номер начального слайдера - прыгает до него без анимации.

2021-12-03 12:15 UTC, bonkalol commented on src/base/b-slider/test/runners/gestures.js
> +			expect(await current(component)).toBe(2);
Тут бы еще проверять установился ли нужный оффсет

2021-12-03 12:15 UTC, bonkalol commented on src/base/b-slider/test/runners/gestures.js
> +			expect(await current(component)).toBe(2);
В других местах где current проверяешь тоже самое

2021-12-03 12:17 UTC, bonkalol commented on src/base/b-slider/test/runners/gestures.js
> +		it('fast swipe', async () => {
Быстрый небольшой свайп - давай так, чтобы проверить что при небольшом но быстром свайпе происходит прокрутка

2021-12-03 12:19 UTC, bonkalol commented on src/base/b-slider/CHANGELOG.md
> +* Wrapped the animations in `requestAnimationFrame`.
Оберни в ссылку на issue

2021-12-03 12:19 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	protected get needReduceMotion(): boolean {
shouldReduceMotion?

2021-12-03 12:19 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +	protected get needReduceMotion(): boolean {
preferReduceMotion?

2021-12-03 12:20 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +			this.async.requestAnimationFrame(this.updateSlidePosition, {label: $$.performSliderMove});
else отбей пустой строкой

2021-12-03 12:30 UTC, bonkalol commented on src/base/b-slider/b-slider.ts
> +			this.async.requestAnimationFrame(this.updateSlidePosition, {label: $$.performSliderMove});
здесь eslint кричит что метод unbound, привяжи к нему контекст `this.updateSlidePositon.bind(this)`

2021-12-06 13:40 UTC, kobezzza approved these changes

2021-12-06 13:57 UTC, merged