EDADEALFRONTEND-4610
V4Fire/Client pull request #760
Opened 2022-12-12 10:35 UTC by Razdva122

2022-12-13 13:18 UTC, Razdva122 commented on src/form/b-checkbox/b-checkbox.ts
> +				this.setValidationMsg(this.getValidatorMsg(false, msg, this.i18n('Required field')), showMsg);
Ошибся, исправил

2022-12-19 09:18 UTC, kobezzza commented on src/lang/index.ts
> +ctx.keys().forEach((path: string) => {
Посмотри как сделано в https://github.com/V4Fire/Client/blob/master/src/traits/i-icon/modules/icons.ts#L38

Это нужно, чтобы require.context работал с поддержкой слоев.

Подробности тут: https://github.com/V4Fire/Client/blob/master/build/monic/require-context.js#L35

2022-12-19 09:36 UTC, kobezzza commented on src/super/i-block/i-block.ts
> +		return i18n(this.componentName);
А как будет работать эта логика с наследованием. Типо есть переводы для b-select, а для b-custom-select нет. Кажется, тут напрашивается еще один параметр - i18nKeyset

2022-12-19 09:37 UTC, kobezzza commented on src/form/b-select-date/const.ts
> +	i18n('b-select-date')('January'),
Захардкоженое имя тут не гуд. Сломается при наследовании.

2022-12-19 10:01 UTC, Razdva122 commented on src/form/b-select-date/const.ts
> +	i18n('b-select-date')('January'),
Тут ведь в рантайме никакого имени не будет, оно при инциализации превратится в массив со строками в нужном переводе? Если выбран русский язык будет массив `[Январь, Феварль, и т.д]` И компоненты которые наследовались будут как и раньше с ним работать

2022-12-20 14:46 UTC, kobezzza commented on build/webpack/alias.js
> +	[`${pzlr.projectName}/translations`]: resolve.sourceDir,
А зачем это нужно? Для спрайтов оно то понятно - они могут храниться в разных папках в зависимости от проекта, но здесь же другой паттерн

2022-12-21 07:23 UTC, Razdva122 commented on build/webpack/alias.js
> +	[`${pzlr.projectName}/translations`]: resolve.sourceDir,
requireContextReplacer, работает с абсолютными путями. И тут два варианта либо мы в флаги моника складываем абсолютные пути до каждого проекта, либо создаем алиасы
@edadeal/core/translations - foo
@v4fire/core/translations - bar
И в монике используем их, мне второй вариант показался, более красивым

2022-12-21 07:35 UTC, Razdva122 commented on build/webpack/alias.js
> +	[`${pzlr.projectName}/translations`]: resolve.sourceDir,
Посмотрю еще сейчас что можно придумать, чтобы от этого избавиться

2022-12-21 07:46 UTC, Razdva122 commented on build/webpack/alias.js
> +	[`${pzlr.projectName}/translations`]: resolve.sourceDir,
Такой вариант улучшить, но пришлось require-context поправить
https://github.com/V4Fire/Client/pull/760/commits/8494072296f0aa6f3ca06653e83afa8a0b17fe46

2022-12-26 13:58 UTC, kobezzza commented on src/form/b-select-date/const.ts
> +	i18n('b-select-date')('January'),
Ну хотя бы сделать выше константу, чтобы каждый раз не писать одно и тоже

2022-12-29 10:50 UTC, kobezzza commented on src/form/b-select-date/b-select-date.i18n/en.js
> +module.exports = {
Здесь и в других файлах забыл копирайты вставить вверху.

2023-01-11 08:43 UTC, Razdva122 commented on src/super/i-block/i-block.ts
> +		return i18n(this.componentName);
Добавил цепочку наследования у компонентнов

2023-01-17 11:18 UTC, dmitrybrovka commented on src/form/b-input/b-input.i18n/ru.js
> +	"The passwords aren't match": 'Пароли не совпадают'
" -> '

2023-01-18 12:28 UTC, kholstinin requested changes

2023-01-18 12:28 UTC, kholstinin commented on build/ts-transformers/i18n-inheritance-chain.js
> + * ts-transformer adding an inheritance chain to all components for i18n
Побольше бы информации о трансформере и пример добавить неплохо через example

2023-01-18 12:28 UTC, kholstinin commented on build/ts-transformers/i18n-inheritance-chain.js
> +		if (block && block.name !== 'i-block') {
Нужен коммент почему игнорит i-block

2023-01-18 12:28 UTC, kholstinin commented on build/ts-transformers/i18n-inheritance-chain.js
> +module.exports = () => i18nInheritanceChainTransformer;
Давай лучше во всех трансформерах придерживаться сигнатуры при объявлении
```
const transformer = () => (context) => { ... };
module.exports = transformer;
```

2023-01-18 12:28 UTC, kholstinin commented on src/core/kv-storage/engines/README.md
> +It is forbidden to use these symbols in keys and values.
А может можно типы для такого написать?

2023-01-18 12:28 UTC, kholstinin commented on src/core/prelude/i18n/const.ts
> +export const COOKIE_STORAGE_NAME = 'v4storage';
Договорились что поставим любое имя покороче на свой вкус
В яндексе кука называется `yp`

2023-01-19 07:25 UTC, Razdva122 commented on build/ts-transformers/i18n-inheritance-chain.js
> + * ts-transformer adding an inheritance chain to all components for i18n
example добавил

2023-01-19 07:25 UTC, Razdva122 commented on build/ts-transformers/i18n-inheritance-chain.js
> +		if (block && block.name !== 'i-block') {
Написал

2023-01-19 07:25 UTC, Razdva122 commented on src/core/prelude/i18n/const.ts
> +export const COOKIE_STORAGE_NAME = 'v4storage';
Сделал v4s

2023-01-19 07:26 UTC, Razdva122 commented on src/core/kv-storage/engines/README.md
> +It is forbidden to use these symbols in keys and values.
Типы нет, но добавил проверку на отсуствие этих символов при set

2023-02-07 10:53 UTC, kobezzza commented on build/ts-transformers/i18n-inheritance-chain.js
> +'use strict';
Этому трансформеру точно нужен README

2023-02-07 11:05 UTC, kobezzza commented on src/core/kv-storage/engines/README.md
> +# core/kv-storage/engines
Тут надо сам движок вынести в папку и дать ему свой README.

В README описать, что все сетится именно в одну куку и указать ограничение. 

Сам движок лучше назвать cookie просто, т.к. engines/cookie-storage уже оверхедно.

2023-02-07 11:05 UTC, kobezzza commented on src/core/kv-storage/engines/cookie-storage.ts
> +export const cookieStorageDividers = {
Вынести в const

2023-02-07 11:06 UTC, kobezzza commented on src/core/kv-storage/engines/cookie-storage.ts
> +export default class CookieStorageEngine {
```suggestion
Другие движки экспортируют набор преднастроеных движков с разными интерфейсами - тут надо также
```

2023-02-07 11:07 UTC, kobezzza commented on src/core/kv-storage/index.ts
> +export const cookieStorageFactory = (
Это лишнее. Весь смысл в том, чтобы люди использовали один АПИ модуля и просто передавали движки

2023-02-14 12:43 UTC, kobezzza approved these changes

2023-02-14 13:05 UTC, merged