bDynamicPage refactoring
V4Fire/Client pull request #838
Opened 2023-04-27 10:25 UTC by misbiheyv

2023-04-27 12:00 UTC, shining-mind requested changes

2023-04-27 12:00 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/main.ts
> +	test.describe('b-dynamic-page base functional', () => {
поработать над описаниями тестов

2023-04-27 12:05 UTC, misbiheyv commented on src/components/base/b-dynamic-page/test/helpers.ts
> +import type bDynamicPage from 'components/base/b-dynamic-page/b-dynamic-page';
разве импорты типов не одним блоком сверху?

2023-04-28 07:33 UTC, shining-mind requested changes

2023-04-28 07:33 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/helpers.ts
> + * Returns string[]
Стоит описать смысл возвращаемого значения, а не тип. Тип и так виден в сигнатуре

2023-04-28 07:33 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/keep-alive.ts
> +		test('should not `include` any components, because function-matcher always returns `null`', async ({page}) => {
я бы написал так:

should not \`include\` components when function-matcher returns \`null\`

аналогично для тестов ниже

2023-04-28 07:33 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/keep-alive.ts
> +		test('should `include` components, that same as function-matcher`s returns string', async ({page}) => {
should include components whose name matches returned from the function-matcher

2023-04-28 07:33 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/keep-alive.ts
> +		test('should `include` components, defined as a function that returns the cache strategy', async ({page}) => {
вот такой перевод выдает Яндекс переводчик:
```
должен "включать" компоненты, определенные как функция, которая возвращает стратегию кэширования
```

по-моему это неверное описание

2023-04-28 07:33 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/keep-alive.ts
> +			test.expect(await target.evaluate(switcher)).toEqual([
не пофикшен формат асинхронного теста

2023-04-28 07:33 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/main.ts
> +	test("shouldn't cache the `component` getter", async ({page}) => {
`...component's getter`

2023-04-28 10:09 UTC, shining-mind requested changes

2023-04-28 10:09 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/keep-alive.ts
> +		'includes specified pages in `keepAlive` caching. When props is empty all loaded pages will be cached'
`When prop...`

2023-04-28 10:09 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/keep-alive.ts
> +		test('should not `include` components not from an array of string names', async ({page}) => {
Предложения с двойным отрицанием плохо воспринимаются, лучше так:


should exclude components that are not part of an array containing string names

2023-04-28 10:09 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/keep-alive.ts
> +		test('should `include` the components matches with a regular expression', async ({page}) => {
should include the components that match a given regular expression

2023-04-28 10:09 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/main.ts
> +	test("shouldn't cache the component's getter", async ({page}) => {
...the `component` getter...

смысл разный.

Сейчас получается смысл такой:

не должен кэшировать геттер компонента 

а должен быть такой:

не должен кэшировать геттер `компонент`

2023-04-28 10:09 UTC, shining-mind commented on src/components/base/b-dynamic-page/test/unit/main.ts
> +	test('should be the same: fields `page` and `componentName`', async ({page}) => {
fields `page` and `componentName` should be equal

2023-04-28 11:26 UTC, shining-mind approved these changes

2023-05-19 14:53 UTC, kobezzza approved these changes

2023-05-19 14:53 UTC, merged