WIP: Update eslint and linters
V4Fire/Client pull request #842
Opened 2023-05-02 09:44 UTC by kholstinin

2023-05-17 10:11 UTC, shining-mind requested changes

2023-05-17 10:11 UTC, shining-mind commented on src/base/b-bottom-slide/b-bottom-slide.ts
> +	 * the cursor direction will be taken into account, but not the nearest step
Не будет ли проблем с выводом описания параметра в документации из-за отсутствия отступа?

2023-05-17 10:11 UTC, shining-mind commented on src/base/b-dynamic-page/b-dynamic-page.ts
> +	 * a string key to cache (it uses instead of a component name),
Здесь аналогичный вопрос: не потеряется ли описание 3 пункта из-за отсутствия отступа

2023-05-17 10:11 UTC, shining-mind commented on src/form/b-button/test/unit/functional.ts
> +				await buttonNode.click();
очень странный фикс, почему удалилась переменная

2023-05-17 10:13 UTC, kholstinin commented on src/core/component/interface/component.ts
> +	activate(_force?: boolean): void {}
Это договоренность, все неиспользуемые аргументы помечаются в начале _

2023-05-17 10:14 UTC, kholstinin commented on src/form/b-button/test/unit/functional.ts
> +				await buttonNode.click();
Это линтер на playwright, использовать force плохо, этим занималась Настя

2023-05-17 10:14 UTC, kholstinin commented on src/base/b-dynamic-page/b-dynamic-page.ts
> +	 * a string key to cache (it uses instead of a component name),
Надо проверить как генерится дока через typedoc и важны ли там эти отступы

2023-05-17 10:15 UTC, shining-mind commented on src/form/b-button/test/unit/functional.ts
> +				await buttonNode.click();
Ну, такое решение всё-таки должен принимать программист, а не линтер

2023-05-17 10:16 UTC, shining-mind commented on src/base/b-dynamic-page/b-dynamic-page.ts
> +	 * a string key to cache (it uses instead of a component name),
@kholstinin проверишь?

2023-05-17 10:31 UTC, shining-mind requested changes

2023-05-17 10:31 UTC, shining-mind commented on src/super/i-block/directives/event/index.ts
> +		group = isObj ? p.value.group : `v-e:${p.arg}`,
это не эквивалетное выражение

2023-05-17 10:31 UTC, shining-mind commented on src/super/i-input/i-input.ts
> +			return Object.isPlainObject(err) ? msg[err.name]! : defMsg;
не эквивалентное выражение

2023-05-17 10:31 UTC, shining-mind commented on src/traits/i-lock-page-scroll/README.md
> +  /** {link iLockPageScroll.enlockable} */
какой-то косяк тут с link

2023-05-17 10:31 UTC, shining-mind commented on src/traits/i-open-toggle/README.md
> +  /** {link iOpenToggle.toggle} */
косяк

2023-05-17 10:31 UTC, shining-mind commented on src/traits/i-open/README.md
> +  /** {link iOpen.open} */
косяк

2023-05-17 10:31 UTC, shining-mind commented on tests/helpers/dom/index.ts
> +		return ctx.click(this.getRefSelector(refName), {...clickOpts});
Тоже вопрос с force

2023-05-17 10:33 UTC, kholstinin commented on src/form/b-button/test/unit/functional.ts
> +				await buttonNode.click();
Нет, это просто плохой тон, как писать тесты через pause, а не wait конкретного события, это потенциально создает очень нестабильный тест

2023-05-17 10:33 UTC, kholstinin commented on src/form/b-button/test/unit/functional.ts
> +				await buttonNode.click();
Нужно избегать такого, как !important в css, а если без этого ну никак ставить ignore и защищаться на ревью)

2023-05-17 11:10 UTC, kholstinin commented on src/base/b-dynamic-page/b-dynamic-page.ts
> +	 * a string key to cache (it uses instead of a component name),
У клиента нет typedocа

2023-05-17 11:28 UTC, shining-mind commented on src/base/b-dynamic-page/b-dynamic-page.ts
> +	 * a string key to cache (it uses instead of a component name),
@kholstinin ну, линтеры же будут на все проекты распространяться, надо как-то проверить

2023-05-18 09:33 UTC, kobezzza commented on .eslintrc.js
> +'use strict';
Копирайты

2023-05-18 09:33 UTC, kobezzza commented on build/ds/index.js
> + * * An array of theme names to include them to the build.
Почему эти правки? Там же mardown список в описании

2023-05-22 06:30 UTC, closed without merging