feat(b-list): Added ability to exclude an item from being selected
V4Fire/Client pull request #844
Opened 2023-05-04 10:49 UTC by geopr

2023-05-04 10:54 UTC, shining-mind requested changes
Надо ручками сделать аналогичный коммит в v4 с учётом изменений в новой ветке.

2023-05-04 10:54 UTC, shining-mind commented on src/traits/i-active-items/i-active-items.ts
> +		const item = ctx.items?.find((item) => item.value === value);
Не очень хорошо искать так, стоит добавить контракт на метод в ctx, который возвращает item по value.

2023-05-04 10:54 UTC, shining-mind commented on src/traits/i-active-items/i-active-items.ts
> +		if (!this.isSelectable(ctx, value)) {
А это не должно распространяться на setActive, unsetActive?

2023-05-04 10:56 UTC, shining-mind commented on src/traits/i-active-items/interface.ts
> +	 * True if item can be selected
Название не очень удачное с учётом, что трейт называется active items

2023-05-04 11:02 UTC, geopr commented on src/traits/i-active-items/i-active-items.ts
> +		const item = ctx.items?.find((item) => item.value === value);
Тут и так контракт на `items` же. Тип `TraitComponents` определен как `iBlock & iActiveItems`

2023-05-04 11:02 UTC, geopr commented on src/traits/i-active-items/i-active-items.ts
> +		if (!this.isSelectable(ctx, value)) {
В `setActive` это есть, а на `unsetActive` не должно

2023-05-04 11:08 UTC, dmitrybrovka commented on src/traits/i-active-items/i-active-items.ts
> +	protected static isSelectable(ctx: TraitComponent, value: unknown): boolean {
Описание

2023-05-04 11:23 UTC, shining-mind commented on src/traits/i-active-items/interface.ts
> +	canBeActive?: boolean;
Может лучше так `activatable`?

2023-05-04 11:35 UTC, geopr commented on src/traits/i-active-items/interface.ts
> +	canBeActive?: boolean;
Думал сначала так, да, но смутило, что в инглише такого слова нету)

2023-05-04 11:50 UTC, shining-mind commented on src/traits/i-active-items/interface.ts
> +	canBeActive?: boolean;
Ну, вроде как такое слово используется, можно ещё назвать `canBeActivated`

2023-05-04 11:54 UTC, geopr commented on src/traits/i-active-items/interface.ts
> +	canBeActive?: boolean;
Переименовал в `activatable` в итоге

2023-05-04 11:55 UTC, shining-mind commented on CHANGELOG.md
> +* Added ability to exclude an item from being activated `i-active-items`
... activated in `i-active-items` trait

2023-05-04 12:04 UTC, shining-mind requested changes
Про b-tree забыл, он тоже расширяет этот трейт.

2023-05-04 12:04 UTC, shining-mind commented on src/base/b-list/b-list.ts
> +	values!: Map<unknown, MapItem>;
Это BR, так делать не надо.

2023-05-04 12:15 UTC, shining-mind commented on src/base/b-list/b-list.ts
> +	*/
Поехал коммент

2023-05-04 12:19 UTC, shining-mind approved these changes

2023-05-05 10:04 UTC, shining-mind requested changes

2023-05-05 10:04 UTC, shining-mind commented on src/traits/i-active-items/README.md
> +Specifies if item is active at the current time.
Некорректное описание, за текущий момент отвечает свойство active у компонента, это скорее про начальное состояние

2023-05-05 11:15 UTC, kobezzza approved these changes

2023-05-05 11:16 UTC, shining-mind approved these changes

2023-05-05 11:16 UTC, merged