feat(i-active-items): Added ability to exclude an item from being act…
V4Fire/Client pull request #845
Opened 2023-05-04 12:43 UTC by geopr

…ivated

2023-05-04 12:50 UTC, shining-mind requested changes

2023-05-04 12:50 UTC, shining-mind commented on CHANGELOG.md
> +## v??.??.?? (2023-??-??)
`v4.??.?? ...`

2023-05-04 12:50 UTC, shining-mind commented on src/components/base/b-list/b-list.ts
> +	getItemByValue(value: Item['value']): CanUndef<Item> {
А чем не подошел `this['Item']['value']`?

2023-05-04 12:50 UTC, shining-mind commented on src/components/base/b-list/modules/values.ts
> +	getItem(value: Item['value']): CanUndef<Item> {
По-моему название должно быть `getItemByValue`

2023-05-04 12:50 UTC, shining-mind commented on src/components/base/b-tree/test/unit/active-items.ts
> +		test('should not be changeable with `activatable = false`', async ({page}) => {
Нужно в описании указать, что activatable задается именно для item'a

2023-05-04 12:50 UTC, shining-mind commented on src/components/traits/i-active-items/i-active-items.ts
> +	 *
Здесь не нужен отступ

2023-05-04 12:58 UTC, geopr commented on src/components/base/b-list/modules/values.ts
> +	getItem(value: Item['value']): CanUndef<Item> {
Ага, сверху два метода тоже переименовал

2023-05-04 12:59 UTC, shining-mind requested changes

2023-05-04 12:59 UTC, shining-mind commented on src/components/base/b-list/b-list.ts
> +				id = this.values.getIndexByValue(value);
Ну зачем трогать существующий класс? Это BR

2023-05-04 12:59 UTC, shining-mind commented on src/components/base/b-list/modules/values.ts
> +	getValueByIndex(index: number | string): Item['value'] {
BR...

2023-05-04 13:01 UTC, shining-mind commented on src/components/base/b-list/modules/values.ts
> +	getItem(value: Item['value']): CanUndef<Item> {
Я тут попутал, подумал, что это сам b-list

2023-05-05 08:54 UTC, shining-mind approved these changes

2023-05-05 10:03 UTC, shining-mind commented on src/components/traits/i-active-items/README.md
> +Specifies if item is active at the current time.
Некорректное описание, за текущий момент отвечает свойство active у компонента, это скорее про начальное состояние

2023-05-05 12:11 UTC, kobezzza approved these changes

2023-05-05 12:11 UTC, merged