feat(i-input): added ability to specify a custom validator function
V4Fire/Client pull request #881
Opened 2023-05-29 15:13 UTC by geopr

2023-05-29 15:20 UTC, kobezzza commented on src/super/i-input/i-input.ts
> +			return validator.call(this, params);
Мне кажется не очень удобно налагать контракт на то, что кастомная функция должна вернеть результат нашего валидатора. Лучше сделать это как раз в этом валидаторе.

2023-05-30 09:03 UTC, kobezzza commented on src/super/i-input/README.md
> +The `iInput` class provides two validators out of the box: `required` and `custom`.
Тут надо сделать для каждого валидатора свой заголовок, чтобы можно было ссылку оставлять

2023-05-30 09:40 UTC, kobezzza commented on src/super/i-input/i-input.ts
> +				return {
А почему в этом объекте должны быть такие поля? Еще раз, твоя функция возвращает Unknown

2023-05-30 11:48 UTC, kobezzza commented on src/super/i-input/interface.ts
> +type CustomValidator<CTX, P> = Validator<CTX, P, unknown>;
Почему кастомный валидатор должен принимать контекст компонента? Он скорее всего просто ожидает данные

2023-05-30 11:49 UTC, kobezzza commented on src/super/i-input/i-input.ts
> +				result = await validator.call(this, params);
Прокидывание контекста в стороннюю функцию тут излишне

2023-05-30 13:57 UTC, shining-mind requested changes

2023-05-30 13:57 UTC, shining-mind commented on src/super/i-input/README.md
> +This one's used to specify a custom validator function:
Тоже странная формулировка `this one's used`, весь новый текст лучше прогнать через chat gpt

2023-05-30 13:57 UTC, shining-mind commented on src/super/i-input/i-input.ts
> +		 * Invokes the specified custom validator function with additional provided parameters
Прогони комментарий через chat gpt, можно вместе с исходным кодом

2023-05-30 13:57 UTC, shining-mind commented on src/super/i-input/i-input.ts
> +		 * @param validator
параметр описан неверно, тут должен быть объект, а `validator` -  это его свойство

2023-05-30 13:57 UTC, shining-mind commented on src/super/i-input/interface.ts
> +type CustomValidator<P> = (params: P) => unknown;
А почему кастомный валидатор возвращает unknown вместо результата?

2023-05-30 14:26 UTC, geopr commented on src/super/i-input/interface.ts
> +type CustomValidator<P> = (params: P) => unknown;
<img width="940" alt="Screen Shot 2023-05-30 at 17 24 20" src="https://github.com/V4Fire/Client/assets/65154994/f17b8eb3-e80c-4fca-b168-a57ba073f38c">

2023-05-30 14:52 UTC, shining-mind approved these changes

2023-05-31 11:38 UTC, kobezzza approved these changes

2023-05-31 11:48 UTC, merged