Add tests for v-bind-with
V4Fire/Client pull request #900
Opened 2023-06-23 19:43 UTC by kormanowsky

#898

2023-06-23 19:45 UTC, kormanowsky commented
промисы как будто не работают, пока .skip им написал

2023-06-26 08:43 UTC, kormanowsky commented
@kobezzza интересный факт (который немного не бьется с примерами к директиве). 
Если в разметке написать
```
<div v-bind-with = { & 
promise: new global.Promise(resolve => resolve()),
then: () => console.log('ok')
} .
```
то все работает. 

Если в тесте написать 
```js
{ 
   promise: new Promise(...),
}
```
падает с ошибкой promise.then is not a function. 
В то время как 
```js
{ 
   promise: () => new Promise(...),
}
```
работает корректно. Такой вариант нашел, изучая доку по Async.

2023-06-26 11:20 UTC, kormanowsky commented
Также в типе поля emitter не хватало, что это может быть просто .on-функция

2023-06-26 14:43 UTC, kobezzza commented on src/components/directives/bind-with/test/unit/main.ts
> +	test('handler execution on event emission', async ({page}) => {
Мы стремимся писать тесты как продолжение доки (BDD нотация). Зарефактори. Для написания хороших описаний рекомендую поставить genesis-bot и использовать chat-gpt.

Пример BDD теста - https://github.com/V4Fire/Client/blob/v4/src/components/base/b-remote-provider/test/unit/events.ts

2023-06-26 14:54 UTC, shining-mind requested changes

2023-06-26 14:54 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +import test from 'tests/config/unit/test';
Надо исправить порядок импортов, от более общего к частному. Примеры можно посмотреть в тестах b-list, b-tree и т.д.

2023-06-26 14:54 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +interface BindWithTestCallInfo {
создайл файл interface.ts в директории `bind-with/unit` и перенеси интерфейсы туда, смотри примеры в тестах b-router

2023-06-26 14:54 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +	test.afterEach(async ({page}) => {
Этот хук лишний, т.к. playwright запускает каждый тест изолированно. Очищать компоненты не надо.

2023-06-26 19:24 UTC, kormanowsky commented on src/components/directives/bind-with/test/unit/main.ts
> +		const newInfo: BindWithTestInfo = {
В какой файл лучше посмотреть?

2023-06-27 09:18 UTC, shining-mind requested changes

2023-06-27 09:18 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +		rootHandle = (await Component.getComponentByQuery(page, '#root-component'))!;
есть хелпер `Component.waitForRoot()`

2023-06-27 09:18 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +	test('when event is emitted, handler is executed', async ({page}) => {
Порядок слов неудачный, лучше читалось бы: `handler is executed when event is emitted`

Ещё обычно мы добавляем слово should, тогда предложение можно было бы переписать так:

`the handler should be executed when the event is emitted`

2023-06-27 09:18 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +	test('when event is emitted, handler is executed', async ({page}) => {
Актуально для всех описаний ниже

2023-06-27 09:21 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +test.describe('<div v-bind-with>', () => {
Обычно в треугольные скобки мы заключаем только название компонента, а здесь директива.

2023-06-27 09:25 UTC, shining-mind commented
> @kobezzza интересный факт (который немного не бьется с примерами к директиве). Если в разметке написать
> 
> ```
> <div v-bind-with = { & 
> promise: new global.Promise(resolve => resolve()),
> then: () => console.log('ok')
> } .
> ```
> 
> то все работает.
> 
> Если в тесте написать
> 
> ```js
> { 
>    promise: new Promise(...),
> }
> ```
> 
> падает с ошибкой promise.then is not a function. В то время как
> 
> ```js
> { 
>    promise: () => new Promise(...),
> }
> ```
> 
> работает корректно. Такой вариант нашел, изучая доку по Async.

Касательно данного замечания. Дело в том, что атрибуты, которые ты пробрасываешь из теста - они сериализуются, а затем десериализуются в контексте браузера. Потому нельзя пробросить промис, а вот функцию можно, потому что одна будет преобразована в строку, а затем eval'ом выполнена в браузере. Можно глянуть тут: https://github.com/V4Fire/Client/blob/611f641ff486fc63a63533d4a7309a06c9b0063c/src/core/prelude/test-env/components/json.ts#L51

2023-06-28 08:37 UTC, kobezzza commented on src/components/directives/bind-with/test/unit/main.ts
> +		await rootHandle.evaluate((root) => {
После каждого многострочного блока обязательно должна быть отбивка переводами строк. Вот так

```
const divLocator = await createDivForBindWithTest(page, {
	on: 'testEvent'
});
		
await rootHandle.evaluate((root) => {
```

2023-06-28 13:28 UTC, shining-mind requested changes

2023-06-28 13:28 UTC, shining-mind commented on src/components/directives/bind-with/test/helpers.ts
> +
здесь по-моему пробел перед фигурной скобкой лишний

2023-06-28 13:28 UTC, shining-mind commented on src/components/directives/bind-with/test/helpers.ts
> +
здесь отбивка отступами не нужна

2023-06-28 13:28 UTC, shining-mind commented on src/components/directives/bind-with/test/helpers.ts
> +
лишний отступ

2023-06-28 13:28 UTC, shining-mind commented on src/components/directives/bind-with/test/helpers.ts
> +
лишний отступ

2023-06-28 13:28 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +
лишний отступ

2023-06-28 13:28 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +
аналогично ниже

2023-06-28 13:28 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +	test('the handler should be executed when provided emitter emits an event', async ({page}) => {
`...when the provided emitter...`

2023-06-28 13:28 UTC, shining-mind commented on src/components/directives/bind-with/test/unit/main.ts
> +		const bodyHandle = await page.evaluateHandle(() => document.body);
кажется, что нет смысла создавать bodyHandle, а можно все сделать в рамках page.evaluate

2023-06-28 13:40 UTC, shining-mind approved these changes

2023-06-29 10:06 UTC, kobezzza commented on src/components/directives/bind-with/test/helpers.ts
> +function handler(element: HTMLElement, ...args: any[]) {
Аналогичные замечания как и в https://github.com/V4Fire/Client/pull/905/files#diff-7bae537e59fcbe05ae23f22ce215016d1f3dc8d445fc8f605f259954abe149c0

2023-06-30 13:16 UTC, kobezzza commented on src/components/directives/bind-with/test/unit/main.ts
> +	test('the handler should be executed when an event is emitted', async ({page}) => {
Тут хорошо на несколько describe побить: для событий, промисов, колбеков, наблюдений за свойствами

2023-06-30 15:27 UTC, kobezzza approved these changes

2023-06-30 15:29 UTC, kobezzza approved these changes

2023-06-30 15:29 UTC, merged