Issues/904
V4Fire/Client pull request #905
Opened 2023-06-27 22:51 UTC by kormanowsky

#904

2023-06-28 09:21 UTC, shining-mind requested changes

2023-06-28 09:21 UTC, shining-mind commented on src/components/directives/in-view/test/helpers.ts
> +		JSON.parse(
Немного непонятно, а зачем тут JSON.parse, если далее у нас parseInt?

2023-06-28 09:21 UTC, shining-mind commented on src/components/directives/in-view/test/helpers.ts
> +	const nextValue = previousValue + 1;
Добавь отступ перед этой строкой

2023-06-28 09:21 UTC, shining-mind commented on src/components/directives/in-view/test/helpers.ts
> +	await page.evaluate(() => globalThis.scrollTo({left: 0, top: 0}));
Есть хелпер [`Scroll`](https://github.com/V4Fire/Client/tree/v4/tests/helpers/scroll)

2023-06-28 09:21 UTC, shining-mind commented on src/components/directives/in-view/test/helpers.ts
> +	await page.setViewportSize({width: 500, height: TEST_DIV_MARGIN_TOP_PX / 2});
Обычно viewport задается с помощью test.use, вот пример:

https://github.com/V4Fire/Client/blob/469f64dd4cbcdccbbb71e08ea1f0ee4118fa4fdf/src/components/base/b-bottom-slide/test/unit/events.ts#L31-L37

2023-06-28 09:21 UTC, shining-mind commented on src/components/directives/in-view/test/unit/main.ts
> +		test.expect(await getWatcherCallsCount(divLocator)).toBe(1);
мы стараемся записывать так: 

```TS
await test.expect(getWatcherCallsCount(divLocator)).resolves.toBe(1)
```
или

```TS
await test.expect(getWatcherCallsCount(divLocator)).toBeResolvedTo(1)
```

лучше читается когда await идет в начале строки

2023-06-28 09:21 UTC, shining-mind commented on src/components/directives/in-view/test/unit/main.ts
> +	test('handler should be called when element enters viewport', async ({page}) => {
`... when the element enters the viewport`

надо проверить все описания, чтобы корректно артикли были расставлены

2023-06-28 09:25 UTC, shining-mind commented on src/components/directives/in-view/test/unit/main.ts
> +		await makeEnterViewport(divLocator);
Я бы отбил отступами блок 

```TS
		await makeEnterViewport(divLocator);
		await restoreViewport(page);
```

2023-06-28 12:05 UTC, kormanowsky commented on src/components/directives/in-view/test/helpers.ts
> +	await page.setViewportSize({width: 500, height: TEST_DIV_MARGIN_TOP_PX / 2});
Я не хочу тащить в код тестов константу TEST_DIV_MARGIN_TOP_PX, а если эту вызвать из хелпера, то получим Most common reasons include:
    - You are calling test.use() in a configuration file.
    - You are calling test.use() in a file that is imported by the configuration file.
    - You have two different versions of @playwright/test. This usually happens
      when one of the dependencies in your package.json depends on @playwright/test.

2023-06-28 12:16 UTC, shining-mind commented on src/components/directives/in-view/test/helpers.ts
> +	await page.setViewportSize({width: 500, height: TEST_DIV_MARGIN_TOP_PX / 2});
test.use надо вызывать в самом файле тестов, не вижу какой-то большой проблемы с тем, чтобы константу импортировать в тест

в целом не настаиваю на таком решении

2023-06-28 12:20 UTC, shining-mind requested changes

2023-06-28 12:20 UTC, shining-mind commented on src/components/directives/in-view/test/helpers.ts
> +	return parseInt(JSON.parse(storedValue), 10);
я про этот момент не писал, думал поправишь - здесь тоже не понятно зачем JSON.parse

2023-06-28 12:20 UTC, shining-mind commented on tests/helpers/scroll/index.ts
> +	static scrollTo(page: Page, opts: ScrollToOptions): Promise<void> {
если добавил новые хелперы, то надо обновить CHANGELOG и README

2023-06-28 12:20 UTC, shining-mind commented on tests/helpers/scroll/index.ts
> +	 * @param options
квадратные скобки нужны, т.к. параметр опциональный:

```
@param [options]
```

Проверь в других местах

2023-06-28 12:49 UTC, shining-mind requested changes

2023-06-28 12:49 UTC, shining-mind commented on tests/helpers/scroll/CHANGELOG.md
> +## v4 (2023-06-28)
Когда неизвестно когда будет мердж, обычно указываем так: 

```md
## v4.??.?? (2023-??-??)
```

А также новые версии нужно добавлять вверх файла

2023-06-28 12:49 UTC, shining-mind commented on tests/helpers/scroll/README.md
> +await Scroll.scrollToBottom(page);
scrollToBottom?

2023-06-28 12:58 UTC, shining-mind requested changes

2023-06-28 12:58 UTC, shining-mind commented on src/components/directives/in-view/test/unit/main.ts
> +	test('handler should be called when the element enters viewport', async ({page}) => {
`the handler ... enters the viewport`

2023-06-28 12:58 UTC, shining-mind commented on src/components/directives/in-view/test/unit/main.ts
> +	test('handler should be called only once if `once` is set', async ({page}) => {
```
the handler ... when the `once` is set
```

2023-06-28 12:58 UTC, shining-mind commented on src/components/directives/in-view/test/unit/main.ts
> +	test('all handlers should be called', async ({page}) => {
из описания непонятно почему все обработчики должны быть вызваны

2023-06-28 13:05 UTC, shining-mind requested changes

2023-06-28 13:05 UTC, shining-mind commented on src/components/directives/in-view/test/unit/main.ts
> +	test('all provided handlers should be called', async ({page}) => {
Я бы всё-таки добавил причину, по идее она такая же как и в первом тесте: `when the element enters the viewport`. К слову в первом тесте не хватает артикля `the` перед словом `viewport`

2023-06-28 13:17 UTC, shining-mind approved these changes

2023-06-29 10:00 UTC, kobezzza commented on src/components/directives/in-view/test/const.ts
> + * The top margin of test <div>, in pixels.
Участки с кодом надо брать в апострофы. Если предложение одно, то точку в конце ставить не надо.

Вот так.

```suggestion
 * The top margin of the test `<div>`, in pixels
```

2023-06-29 10:02 UTC, kobezzza commented on src/components/directives/in-view/test/const.ts
> +export const TEST_DIV_MARGIN_TOP_PX = 1000;
Не думаю, что стоит выносить это в отдельный файл const

2023-06-29 10:03 UTC, kobezzza commented on src/components/directives/in-view/test/helpers.ts
> +function handler(watcher: Watcher): void {
Нет смысла выносить в хэлперы такие функции, т.к. вынесение в хэлперы подразумевает переиспользование кода между разными файлами тестов, а тут файл всего один + это реально ухудшает читаемость тестов - приходится смотреть несколько файлов чтобы понять тест

2023-06-29 10:03 UTC, kobezzza commented on src/components/directives/in-view/test/helpers.ts
> + * @param locator - The source locator
После - с маленькой буквы

```suggestion
 * @param locator - the source locator
```

2023-06-29 10:04 UTC, kobezzza commented on src/components/directives/in-view/test/helpers.ts
> + * Force adds test handler (which counts calls) to given watch,
Описание методов должно начинаться с глагола в 3-м лице

2023-06-29 10:04 UTC, kobezzza commented on src/components/directives/in-view/test/helpers.ts
> +): WatchHandler | WatchOptions & { handler: WatchHandler } {
Пробелы по краям не нужны

```suggestion
): WatchHandler | WatchOptions & {handler: WatchHandler} {
```

2023-06-29 10:05 UTC, kobezzza commented on src/components/directives/in-view/test/unit/main.ts
> +
```suggestion
```

2023-06-29 10:06 UTC, kobezzza commented on src/components/directives/in-view/test/unit/main.ts
> +test.describe('components/directives/in-view', () => {
Все таки хочется тестирования больших кейзов функциональности директивы, см модуль core/dom/intersection/watcher

2023-06-30 13:23 UTC, merged