WIP: add tests for v-image
V4Fire/Client pull request #909
Opened 2023-06-28 17:32 UTC by kormanowsky

#906

2023-06-29 09:27 UTC, shining-mind requested changes

2023-06-29 09:27 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		const {divLocator} = await createDivForTest(page, {src: EXISTING_PICTURE_SRC});
Надо больше воздуха добавить

2023-06-29 09:27 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +	test('the provided prefix should be used as prefix for `src` attribute', async ({page}) => {
```
... as a prefix ...for the `src` attribute
```

2023-06-29 09:27 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +	test('the `srcset` attribute of img should be set if provided', async ({page}) => {
`... of the img ...`

`if provided` - кажется лишним

2023-06-29 09:27 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +	test('the `width` and the `height` attributes should be set to provided values', async ({page}) => {
`to provided values` - тоже можно опустить

2023-06-29 09:27 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test.expect(span.dataImage).toBe('preview');
воздуха надо добавить

2023-06-29 13:57 UTC, shining-mind approved these changes

2023-07-03 11:31 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +			divLocator,
Сделай нормальные имена свойствам, например, imageWrapper и image

2023-07-03 11:31 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +				'data-testid': 'div'
Тут тоже лучше нормальные ИД-ники давать

2023-07-03 11:32 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	async function createDivForTest(
Очень странное название и именование - createImage

2023-07-03 11:32 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	 * @param page - The target page.
```suggestion
	 * @param page
```

2023-07-03 11:32 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	 * @param imageValue - The value of v-image directive.
```
	 * @param imageOpts- options for the `image` directive
```

2023-07-03 11:33 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	 * @param [divAttributes] - Optional attributes for created <div>.
```
	 * @param [attrs] - additional attributes for the element to which the directive is applied
```

2023-07-03 11:34 UTC, kobezzza commented on src/components/directives/image/test/helpers.ts
> +async function getImageTestImgData(imgLocator: Locator): Promise<ImageTestImgData> {
Я не уверен, что хорошая идея делать такие хэлперы.

В тесте становиться совсем не понятно, что это за свойства такие. Гораздо декларативнее будет если ты явно будешь получать атрибуты в каждом тесте

2023-07-03 11:35 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +		test.expect(span.dataImage).toBe('preview');
Если изображение загрузилось, то почему тут preview?

2023-07-03 11:35 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	test('the provided main image should be shown when loaded successfully', async ({page}) => {
Этот тест про смену статуса в дата атрибутах же

2023-07-03 11:36 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	test('the provided prefix should be used as a prefix for `src` attribute', async ({page}) => {
описание не отражает смысла

2023-07-03 11:36 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	test('the `srcset` attribute should be set', async ({page}) => {
Тут тоже описание бессмысленное

2023-07-03 11:37 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	test('the `width` and the `height` attributes should be set', async ({page}) => {
Еще раз, смысл описания теста в том, чтобы служить документацией.

Здесь тест должен звучать следущим образом: опции width и height должны устанавливаться как атрибуты тега Img

2023-07-03 11:37 UTC, kobezzza commented on src/components/directives/image/test/unit/main.ts
> +	test('the `sizes` attribute should be set', async ({page}) => {
Здесь и ниже ужасные описания

2023-07-03 12:40 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
В directives/icon так же. Если убрать div, то playwright виснет на этапе Component.createComponent

2023-07-03 12:43 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Убрать div ты имеешь в виду прокинуть пустую строку в качестве аргумента?

2023-07-03 12:45 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Имею в виду вместо структуры 
<div>
    (сделает v-image: <span><img /></span>)
</div>

оставить: 
<div></div>(v-image заменит на: <span><img /></span>)

2023-07-03 12:47 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Имеешь в виду, что если пробросить v-image как атрибута самого DIV'a, то он неверно отрендерит изображение? За пределами этого DIV'a?

2023-07-03 12:48 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Если пробросить v-image как самого div-а, тест просто зависнет.

2023-07-03 12:53 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Да, надо разобраться

2023-07-03 13:22 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Проблема в том, что `Component.createComponent()` использует `data-render-id`, которые не сохраняются `v-image`. Такой вариант сработал, но onLoad(), onError() в атрибутах дают `Error: unexpected value`:

```js

await page.evaluate(
			(attrs) => {
				globalThis.renderComponents('div', [{attrs}]);
			},
			{
				...attrs,
				'data-testid': 'imageWrapper',
				'v-image': imageOpts
			}
		);

		await page.waitForSelector('span[data-testid="imageWrapper"]');

		const divLocator = page.getByTestId('imageWrapper');

```

2023-07-03 13:26 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
не понял где именно onLoad и onError дает ошибку

2023-07-03 13:28 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Если передать в imageOpts `{onLoad: () => console.log('it works')}`, получим 

<img width="1170" alt="Screen Shot 2023-07-03 at 16 28 13" src="https://github.com/V4Fire/Client/assets/20301761/5e91f13c-746f-4523-a6b2-1abc2990d011">

2023-07-03 13:42 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Ну, потому что у тебя функция не сериализуется, т.к. ты пробрасываешь объект сам. Когда используешь createComponent там специальная функция, я тебе он ней говорил.

2023-07-03 13:45 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
В итоге: сделать так, как просит @kobezzza здесь не получится.

2023-07-03 13:47 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Ну, надо понять почему Component.createComponent виснет, запусти PW в debug режиме 

2023-07-03 13:47 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
https://github.com/V4Fire/Client/tree/v4/docs/tests#cli-flags

2023-07-03 14:00 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
> Проблема в том, что Component.createComponent() использует рандомные data-render-id, которые не сохраняются v-image.

<img width="596" alt="Screen Shot 2023-07-03 at 15 58 37" src="https://github.com/V4Fire/Client/assets/20301761/6f7d9c48-b94f-4fe3-a8eb-fad879bd6347">

<img width="350" alt="Screen Shot 2023-07-03 at 16 59 40" src="https://github.com/V4Fire/Client/assets/20301761/83f9736f-f403-414b-b3fc-8afe339f1116">

2023-07-03 14:03 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
То есть директива `v-image` дропает все data атрибуты на DIVe?

2023-07-03 14:04 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Не все. По всей видимости, только data-render-id

2023-07-03 14:04 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Вот мой data-testid там есть

2023-07-03 14:05 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Это очень странно, надо попробовать понять почему этот атрибут дропается

2023-07-03 14:20 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Он уходит в v-attrs, который оказывается [object Object]: 

<img width="522" alt="Screen Shot 2023-07-03 at 17 19 06" src="https://github.com/V4Fire/Client/assets/20301761/b5b7c3ee-eaa8-43ec-90b0-3ae406ca3b26">
Вывел в директиве vnode.props:
<img width="561" alt="Screen Shot 2023-07-03 at 17 20 40" src="https://github.com/V4Fire/Client/assets/20301761/312e99bc-be0e-425b-b511-782ece61f56e">

2023-07-03 14:28 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		await Component.createComponent(page, 'div', {
Окей, давай пока оставим вложенный span, надо разбираться почему так, но это выходит за пределы текущей задачи

2023-07-03 15:30 UTC, shining-mind requested changes

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +				'data-testid': 'div'
ID надо переименовать, Андрей об этом написал, назови его хотя бы `container`

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		const imageWrapper = div.locator('span');
можно в одну строчку:

```ts
const imageWrapper = page.getByTestId('container').locator('span')
```

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of image and wrapper should indicate successful load',
the attributes of **the** image and ...

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +			async ({page}) => {
в одну строчку без переноса не входит?

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the initially invisible image should be loaded when `lazy` is set to false',
should be **instantly** loaded

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of image and wrapper should indicate image preview if the image is not loaded yet',
of **the** image

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of image and wrapper should indicate image preview if the image is not loaded yet',
should indicate image preview - должны обозначать превью изображения? какая-то странная формулировка

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of image and wrapper should indicate image preview if the image is not loaded yet',
скорее верно так: должно отображаться превью, пока изображение не загружено

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of image and wrapper should indicate fallback image when main image failed loading',
аналогичные замечания

2023-07-03 15:30 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +	test.describe('options as attributes', () => {
Формулировка не очень понятна, можно написать так: 
```
directive options should be set as `img` attributes
```

2023-07-04 09:18 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of image and wrapper should indicate image preview if the image is not loaded yet',
@kobezzza написал: 

> Этот тест про смену статуса в дата атрибутах же

Отсюда и такие описания

2023-07-04 09:26 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of image and wrapper should indicate image preview if the image is not loaded yet',
Тогда надо написать так: should indicate that image is a preview, иначе бессмыслица получается

2023-07-04 09:28 UTC, kormanowsky commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of image and wrapper should indicate image preview if the image is not loaded yet',
Готово

2023-07-04 09:45 UTC, shining-mind requested changes

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +import { Component } from 'tests/helpers';
Это импорт надо переместить выше, порядок должен быть такой:

```ts
import type { Page } from 'playwright';

import test from 'tests/config/unit/test';
import { Component } from 'tests/helpers';

import type { ImageTestLocators } from 'components/directives/image/test/interface';

import {

	BROKEN_PICTURE_SRC,
	EXISTING_PICTURE_SRC,
	SLOW_LOAD_PICTURE_SRC

} from 'components/directives/image/test/const';

import {

	getPngBuffer,
	waitForAttribute,
	waitForImageLoad,
	waitForImageLoadFail

} from 'components/directives/image/test/helpers';
```

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of the image and the wrapper should indicate successful load', async ({page}) => {
**a** successful load

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of the image and the wrapper should indicate that image is a fallback when main image failed loading',
when **the** main image failed

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of the image and the wrapper should indicate that image is a preview if the image is not loaded yet',
**when the main** image is not loaded yet

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +			async ({page, context}) => {
перенос не исправлен

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the initially invisible image should be instantly loaded when `lazy` is set to false', async ({page}) => {
when **the** lazy is

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the return value of `optionsResolver` should be used instead of provided options', async ({page}) => {
instead of **the** provided

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the provided `onError` handler  should be called on image load error', async ({page}) => {
`handler  should` - лишний пробел

2023-07-04 09:45 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +					type: 'span',
Надо оставить комментарий в коде, почему используется вложенный тег. Надо описать проблему, о которой мы говорили в обсуждении

2023-07-04 11:01 UTC, shining-mind requested changes

2023-07-04 12:31 UTC, shining-mind requested changes

2023-07-04 12:31 UTC, shining-mind commented on src/components/directives/image/test/unit/main.ts
> +		test('the attributes of the image and the wrapper should indicate that image is a fallback when the main image failed loading', async ({page}) => {
that **the** image is a fallback

2023-07-04 12:51 UTC, shining-mind approved these changes

2023-07-26 12:15 UTC, kobezzza approved these changes

2023-07-26 12:15 UTC, merged