Added possibility to prevent link navigate
V4Fire/Client pull request #911
Opened 2023-06-29 13:53 UTC by alexeishcherbina

Added possibility to prevent link navigate by using `CustomEvent` emission in `b-router` and its `preventDefault` method
Added `getHref` method to `b-list` to choose list item tag at the rendering stage

2023-06-29 14:12 UTC, shining-mind requested changes
Нужно написать юнит-тесты на новую функциональность b-router

2023-06-29 14:12 UTC, shining-mind commented on CHANGELOG.md
> +* Added possibility to prevent link navigate
Нужно чуть больше информации: описать принцип и событие

2023-06-29 14:12 UTC, shining-mind commented on src/components/base/b-router/CHANGELOG.md
> +* Added new methods `getHref`
Тут вроде не добавлен getHref

2023-06-29 14:12 UTC, shining-mind commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new Event('linkNavigate', {cancelable: true});
должны передаваться детали о ссылке, тебе нужен CustomEvent. Как минимум там должна быть указана ссылка

2023-06-29 14:59 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new Event('linkNavigate', {cancelable: true});
Могу переделать на CustomEvent, но кажется особой разницы нет, как передавать эти детали: в объекте события или при эмите (как сейчас передаётся href ссылки)

2023-06-29 15:03 UTC, shining-mind commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new Event('linkNavigate', {cancelable: true});
Какой устоявшийся паттерн для передачи аргументов события? Если принято, что аргументы передаются отдельно, то окей. Если все аргументы должны быть в событии, то надо завернуть в CustomEvent

2023-06-29 15:04 UTC, shining-mind commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new Event('linkNavigate', {cancelable: true});
также надо в метод добавить TSDOC `@emits`

2023-07-06 13:31 UTC, alexeishcherbina commented on CHANGELOG.md
> +* Added possibility to prevent link navigate
Добавил немного информации

2023-07-06 13:31 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new Event('linkNavigate', {cancelable: true});
Переделал на `CustomEvent` и поправил tsdoc

2023-07-06 13:42 UTC, shining-mind requested changes

2023-07-06 13:42 UTC, shining-mind commented on CHANGELOG.md
> +* Added new method `getHref`
Непонятно к какому компоненту это относится

2023-07-06 13:42 UTC, shining-mind commented on CHANGELOG.md
> +* Added possibility to prevent link navigate by blocking the new CustomEvent `linkNavigate`
Аналогично

2023-07-06 13:42 UTC, shining-mind commented on src/components/base/b-router/CHANGELOG.md
> +* Added possibility to prevent link navigate by blocking the new CustomEvent `linkNavigate`
Немного некорректное описание. Непонятно при чём тут `new CustomEvent`, почему он `new`. `blocking` - это явно не тот термин, мы вызываем метод preventDefault

2023-07-06 13:42 UTC, shining-mind commented on src/components/base/b-router/modules/handlers.ts
> + * @emits `linkNavigate(event:` [[CustomEvent]]`)`
Надо описать, что содержится в CustomEvent

2023-07-06 13:42 UTC, shining-mind commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new CustomEvent('linkNavigate', {
почему событие просто не назвать navigate или navigation?

2023-07-06 13:42 UTC, shining-mind commented on src/components/base/b-router/test/helpers.ts
> -import { Component, Utils } from 'tests/helpers';
А для чего изменил порядок импортов:?

2023-07-06 13:42 UTC, shining-mind commented on src/components/base/b-router/test/helpers.ts
> +		link = document.createElement('a');
Обычно мы исходный компонент со всеми необходимым DOM узлами рендерим с помощью функции: `Component.createComponent`.

2023-07-06 13:42 UTC, shining-mind commented on src/components/base/b-router/test/unit/transition.ts
> +		await test.expect(root.evaluate(
не очевидно из самого теста, что здесь слушается событие, посмотри как в других тестах проверяются события

2023-07-06 13:42 UTC, shining-mind commented on src/components/base/b-router/test/unit/transition.ts
> +		await test.expect(root.evaluate(
я бы ещё в тест добавил проверку исходной страницы, так будет нагляднее что действительно навигация была предотвращена

2023-07-06 14:27 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new CustomEvent('linkNavigate', {
На мой взгляд это будет лишним обобщением, мы ведь испускаем это событие только при переходе по ссылке

2023-07-06 14:28 UTC, alexeishcherbina commented on src/components/base/b-router/test/helpers.ts
> -import { Component, Utils } from 'tests/helpers';
Тут порядок не изменился, добавился новый импорт из `iStaticPage`, и случайно затёрлась пустая строка между старыми

2023-07-06 14:30 UTC, shining-mind commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new CustomEvent('linkNavigate', {
Валидно, окей

2023-07-06 15:12 UTC, alexeishcherbina commented on src/components/base/b-router/test/helpers.ts
> +		link = document.createElement('a');
Здесь ссылка нужна только для конкретных тестов, не вижу необходимости подмешивать логику её создания в общий поток тестов компонента. Также внутри `evaluate` проще кликать на ссылку таким способом, как сейчас

2023-07-06 15:19 UTC, alexeishcherbina commented on src/components/base/b-router/test/unit/transition.ts
> +		await test.expect(root.evaluate(
Если ты имел ввиду представление `result` в виде объекта с полями-хранилищами событий, то сделал доработку

2023-07-06 15:19 UTC, alexeishcherbina commented on src/components/base/b-router/test/unit/transition.ts
> +		await test.expect(root.evaluate(
Добавил

2023-07-06 17:06 UTC, alexeishcherbina commented on src/components/base/b-router/test/helpers.ts
> +		link = document.createElement('a');
Перенёс хэлпер в describe

2023-07-07 05:36 UTC, alexeishcherbina commented on CHANGELOG.md
> +* Added new method `getHref`
Поправил

2023-07-07 05:36 UTC, alexeishcherbina commented on CHANGELOG.md
> +* Added possibility to prevent link navigate by blocking the new CustomEvent `linkNavigate`
Поправил

2023-07-07 05:36 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> + * @emits `linkNavigate(event:` [[CustomEvent]]`)`
Добавил коммент

2023-07-07 05:59 UTC, alexeishcherbina commented on src/components/base/b-router/test/unit/transition.ts
> +		await test.expect(root.evaluate(
Этот хэлпер создан, чтобы избавиться от дублирования кода. Если в каждом тесте обрабатывать событие, то этот код почти ничем не будет отличаться, что растянет код и затруднит поддержку

2023-07-07 06:01 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> + * @emits `linkNavigate(event:` [[CustomEvent]]`)` - contains a transition link
Добавил коммент

2023-07-07 07:41 UTC, shining-mind approved these changes

2023-07-11 12:35 UTC, kobezzza commented on src/components/base/b-router/modules/handlers.ts
>  export async function link(this: bRouter, e: MouseEvent): Promise<void> {
Здесь явно кривой мерж. urlsToIgnore содержит в себя и # и javascript

2023-07-11 12:35 UTC, kobezzza commented on src/components/base/b-router/modules/handlers.ts
> +			href
Почему бы не передавать ссылку на элемент, на котором произошло событие? Это может быть полезно для считывания других дата атрибутов

2023-07-11 12:36 UTC, kobezzza commented on src/components/base/b-router/modules/handlers.ts
> +	if (linkNavigateEvent.defaultPrevented || <boolean>Object.parse(a.getAttribute('data-router-prevent-transition'))) {
Почему бы проверку атрибута не вынести в переменную cantPrevent

2023-07-11 12:37 UTC, kobezzza commented on src/components/base/b-router/modules/handlers.ts
> + * @emits `linkNavigate(event:` [[CustomEvent]]`)` - contains a transition link
В README нет информации

2023-07-11 16:45 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> + * @emits `linkNavigate(event:` [[CustomEvent]]`)` - contains a transition link
Добавил информацию в README

2023-07-11 16:51 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
>  export async function link(this: bRouter, e: MouseEvent): Promise<void> {
Действительно, видимо забыли убрать, когда добавили `urlsToIgnore`. Поправил

2023-07-11 16:52 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> +			href
Изменил на передачу элемента

2023-07-11 16:53 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> +	if (linkNavigateEvent.defaultPrevented || <boolean>Object.parse(a.getAttribute('data-router-prevent-transition'))) {
Вынес в `cantPrevent `

2023-07-12 12:22 UTC, kobezzza commented on src/components/base/b-router/modules/handlers.ts
> +			target: a
href зря убрал, это удобно что можно не лазить в атрибуты, а сразу получить ссылку

2023-07-12 12:30 UTC, kobezzza commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new CustomEvent('linkNavigate', {
Проблема такого подхода, что у нас в detail unknown.
Лучше сделать дочерний класс с конкретным типом. Например, таким.

```typescript
class RouterTransitionEvent<T extends Element> extends CustomEvent<{href: string; target: T}> {
	constructor(target: T) {
		super('linkNavigate', {
			cancelable: true,
			detail: {
				href: target.getAttribute('href') ?? '',
				target
			}
		});
	}
}
```

И положить куда-нибудь в modules/transition/event.

+ Надо будет этот класс ре-экспортировать из самого компонента, чтобы другой код могу получить инфу по типам

2023-07-12 12:31 UTC, kobezzza commented on src/components/base/b-router/test/unit/transition.ts
> +								onLinkNavigate: [event.detail?.target?.getAttribute('href')]
Добавишь href, надо не забыть и сюда добавить + тоже укажи новый тип, а не CunstomEvent

2023-07-12 13:33 UTC, alexeishcherbina commented on src/components/base/b-router/modules/handlers.ts
> +	const linkNavigateEvent = new CustomEvent('linkNavigate', {
Добавил дочерний класс, назвал его `LinkNavigateEvent`, т.к. кажется некорректным давать более общее имя, а испускать при этом конкретное событие `linkNavigate `

2023-07-12 13:35 UTC, alexeishcherbina commented on src/components/base/b-router/test/unit/transition.ts
> +								onLinkNavigate: [event.detail?.target?.getAttribute('href')]
Поправил здесь и в README

2023-07-15 04:50 UTC, shining-mind commented on src/components/base/b-router/README.md
> +If you need to disable intercepting a specific link click, you can handle the `hrefTransition` event,
"Если вам надо отключить перехват клика по определенной ссылке", кажется что лучше будет так перевести: "If you need to disable the interception of a click on a specific link".

Потому что сейчас формулировка такая, что не сразу понятно, что отключается перехват клика на ссылке

2023-07-15 04:50 UTC, shining-mind commented on src/components/base/b-router/README.md
> +
Ещё не хватает информации про `stopPropagation`

2023-07-15 04:50 UTC, shining-mind commented on src/components/base/b-router/test/unit/transition/events.ts
> +		'the `softChange` event should only be fired in transitions where only query parameters are changed',
По смыслу данное предложение обозначает, что событие должно быть выброшено, только если изменились query параметры, т.е. об изменении говорим в продшем времени, потому такая формулировка будет лучше:

query parameters **have** changed

2023-07-15 04:50 UTC, shining-mind commented on src/components/base/b-router/test/unit/transition/events.ts
> +		'the `softChange` event should only be fired in transitions where only query parameters are changed',
Актуально для всех описаний ниже

2023-07-15 04:50 UTC, shining-mind commented on src/components/base/b-router/test/unit/transition/parameters.ts
> +			'parameters from `params` should be passed as values into the transition path where `:paramName`constructs are located',
```suggestion
			'parameters from `params` should be passed as values into the transition path where `:paramName` constructs are located',
```

2023-07-19 12:49 UTC, kobezzza approved these changes

2023-07-19 13:18 UTC, merged