feat: added loader for responsive images
V4Fire/Client pull request #975
Opened 2023-09-05 14:25 UTC by geopr

2023-09-05 14:39 UTC, kholstinin requested changes

2023-09-05 14:39 UTC, kholstinin commented on build/webpack/loaders/adapters/scale-image-adapter.js
> +class Adapter {
jsdoc и @see на доку лоадера

2023-09-05 14:39 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> +	path = require('path'),
Для нового нодового кода нодовые зависимости надо писать как `node:path`, `node:vm`

2023-09-05 14:39 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> +	adapter: require('./adapters/scale-image-adapter'),
Адаптер через include надо поключать

2023-09-05 14:39 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> +	outputPath: urlLoaderOpts.outputPath,
Опции отдельно вынести, надо чтобы в конфиге outputPath совпадал

2023-09-05 14:39 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> +	name: isProd ? '[hash]-[width].[ext]' : '[name].[ext]',
Это тоже в конфиг

2023-09-05 14:39 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> +	if (!isProd) {
Может быть просто не применять лоадер совсем, использовать дефолтный конфиг для картинок и решать это на уровне применения лоадеров в webpack/module/rules/image.ts?

2023-09-05 14:39 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> + * Compiles the code returned by the responsiveLoader to the NodeJS module
Более подробный коммент нужен бы

2023-09-05 14:39 UTC, kholstinin commented on build/webpack/module/rules/images.js
> +				use: [{loader: 'responsive-images-loader'}]
Можно просто `use: ['responsive-images-loader']`

2023-09-05 18:53 UTC, gretzkiy commented on build/webpack/loaders/README.md
> +Please note that the image you want to apply the loader to should be 3x resolution of its original size
"3x resolution of its original size" звучит странно. Как раз original size это обычно максимальное разрешение. мне кажется, что тут можно просто написать, что исходная картинка должна быть максимального качества, а из нее будут генерироваться картинки меньшего разрешения

2023-09-05 18:53 UTC, gretzkiy commented on build/webpack/loaders/README.md
> +  // 346 - 2x size of the original image
а что за числа 346, 521, 173? Какая-то абстрактная единица размера?

2023-09-05 18:53 UTC, gretzkiy commented on build/webpack/loaders/adapters/scale-image-adapter.js
> +	metadata() {
Можно геттер сделать

2023-09-05 18:53 UTC, gretzkiy commented on build/webpack/loaders/adapters/scale-image-adapter.js
> +class Adapter {
и на все методы jsdoc с описанием параметров

2023-09-05 18:53 UTC, gretzkiy commented on build/webpack/loaders/responsive-images-loader.js
> +	disable: !isProd
мне кажется, обычно передают параметр, когда включать, а не отключать

2023-09-05 18:53 UTC, gretzkiy commented on build/webpack/loaders/responsive-images-loader.js
> + * It also adds support for scaling images to 1x and 2x resolutions of their original size.
> images to 1x and 2x resolutions

Но разве разрешения нельзя задать свои собственные?

2023-09-05 18:53 UTC, gretzkiy commented on build/webpack/loaders/responsive-images-loader.js
> +		[, [source2xImageName]] = imageNames;
было бы удобно конфигурировать, какую именно использовать как дефолтную

2023-09-06 07:53 UTC, geopr commented on build/webpack/loaders/responsive-images-loader.js
> +	if (!isProd) {
Я так думал, но хотелось бы иметь общий возвращаемый интерфейс и в деве и в проде. В данном случае это `{src: string}`. Если в деве применить другой лоадер, он же вернет строку и вот такой пример сломается?
```ss
< .my-image v-image = {src: require('image.png').src}
```

2023-09-06 07:53 UTC, geopr commented on build/webpack/loaders/responsive-images-loader.js
> +		formats = [undefined, 'webp', 'avif'],
Это для оригинальной картинки. Я не могу тут знать ее формат, поэтому просто не передаю его. Вынес в константу это

2023-09-06 07:55 UTC, geopr commented on build/webpack/loaders/README.md
> +  // 346 - 2x size of the original image
Ширина в пикселях. `[hash]-[width].[ext]`

2023-09-06 07:55 UTC, geopr commented on build/webpack/loaders/adapters/scale-image-adapter.js
> +	metadata() {
Нельзя, там метод ожидается. Добавил jsdoc

2023-09-06 07:56 UTC, geopr commented on build/webpack/loaders/responsive-images-loader.js
> +	disable: !isProd
Это параметры `responsive-loader`, не мои

2023-09-06 07:56 UTC, geopr commented on build/webpack/loaders/responsive-images-loader.js
> + * It also adds support for scaling images to 1x and 2x resolutions of their original size.
Теперь можно

2023-09-06 07:56 UTC, geopr commented on build/webpack/loaders/responsive-images-loader.js
> +		[, [source2xImageName]] = imageNames;
Добавил поддержку

2023-09-06 07:57 UTC, geopr commented on build/webpack/loaders/responsive-images-loader.js
> +	name: isProd ? '[hash]-[width].[ext]' : '[name].[ext]',
Прям все в `config/default`?

2023-09-06 08:35 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> +	name: isProd ? '[hash]-[width].[ext]' : '[name].[ext]',
Ага

2023-09-06 08:36 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> +	if (!isProd) {
Убедил

2023-09-06 08:39 UTC, kholstinin commented on build/webpack/loaders/adapters/scale-image-adapter.js
> +	#convert(image, mimeType, quality) {
А вдруг переопределить надо будет
Лучше не делать методы приватными

2023-09-06 08:39 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> + * Wepback loader for converting and scaling images to different formats and sizes.
Webpack

2023-09-06 08:44 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader.js
> +function parseResourceQuery(query) {
Пример бы что там может быть внутри

2023-09-07 12:11 UTC, shining-mind commented on CHANGELOG.md
> +* Added a new loader for responsive images `responsive-images-loader`
```suggestion
* Added a new webpack loader for responsive images `responsive-images-loader`
```

2023-09-07 12:11 UTC, shining-mind commented on build/webpack/loaders/README.md
> +### symbol-generator-loader
Тут по семантике нужен заголовок 2-го уровня

2023-09-07 12:11 UTC, shining-mind commented on build/webpack/loaders/README.md
> +#### Description
в этом заголовке нет смысла, т.к описание может идти сразу после заголовка лоадера

2023-09-07 12:11 UTC, shining-mind commented on build/webpack/loaders/README.md
> +Please note that the image you want to apply the loader to should be the maximum resolution
```suggestion
Please note that the image you want to apply the loader to should be the maximum resolution.
```

2023-09-07 12:11 UTC, shining-mind commented on build/webpack/loaders/README.md
> +Please note that the image you want to apply the loader to should be the maximum resolution
`should be the maximum resolution` возможно стоит перефразировать

2023-09-13 12:21 UTC, kobezzza commented on build/webpack/loaders/adapters/scale-image-adapter.js
> +/*!
Как будто стоит сделать папку с лоадером и туда вынести это.

2023-09-13 14:07 UTC, bonkalol commented on build/webpack/loaders/responsive-images-loader.js
> +	path = require('path'),
upath же, пощади windows пользователей

2023-09-19 07:32 UTC, kholstinin requested changes

2023-09-19 07:32 UTC, kholstinin commented on build/webpack/module/rules/ts.js
> +	path = require('path');
node:path

2023-09-19 07:32 UTC, kholstinin commented on build/webpack/module/rules/images.js
> +	path = require('path');
node:path

2023-09-19 07:32 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader/index.js
> +			(format) => responsiveLoader.call(createContext(resolve, reject, format), imageBuffer)
А это норм что тут всем contextам отдается один resolve?
Resolve ведь только первый выполнится

2023-09-19 07:32 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader/index.js
> +	if (query[1] !== '{' || query[query.length - 1] !== '}') {
Как то ненадежно выглядит, может просто пытаться запарсить и обернуть в try/catch?

2023-09-19 07:32 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader/index.js
> +	json5 = require('json5'),
json5 надо добавить в список зависимостей

2023-09-19 07:32 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader/adapter.js
> +			convertedImage.toBuffer((err, data, {width, height}) => {
У шарпа есть promise api

2023-09-19 07:32 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader/adapter.js
> +			convertedImage.toBuffer((err, data, {width, height}) => {
Можно всю функцию переписать на обычный async/await

2023-09-19 10:54 UTC, geopr commented on build/webpack/loaders/responsive-images-loader/index.js
> +	json5 = require('json5'),
В package.json?

2023-09-19 11:03 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader/index.js
> +	json5 = require('json5'),
Да, все что requireится и importится в проекте должно быть в прямой зависимости в package.json
Иначе это ghost dependency, а это плохо и ведёт к багам

2023-09-19 11:05 UTC, kholstinin commented on build/webpack/loaders/responsive-images-loader/index.js
> +			(format) => responsiveLoader.call(createContext(resolve, reject, format), imageBuffer)
Как то все равно некрасиво, давай может через Promise.all?

2023-09-19 11:07 UTC, geopr commented on build/webpack/loaders/responsive-images-loader/index.js
> +	json5 = require('json5'),
Добавил

2023-09-19 11:26 UTC, geopr commented on build/webpack/loaders/responsive-images-loader/index.js
> +			(format) => responsiveLoader.call(createContext(resolve, reject, format), imageBuffer)
Я думал, как лучше сделать, но не придумал. Через Promise.all не получится, тк сам вызов `responsiveLoader.call(...)` синхронный: 
- https://github.com/dazuaz/responsive-loader/blob/master/src/index.ts#L46
- https://github.com/dazuaz/responsive-loader/blob/master/src/index.ts#L127

2023-09-19 11:54 UTC, geopr commented on build/webpack/loaders/responsive-images-loader/index.js
> +			(format) => responsiveLoader.call(createContext(resolve, reject, format), imageBuffer)
Да, точно. Переписал

2023-09-19 18:04 UTC, kholstinin approved these changes

2023-09-20 12:40 UTC, merged